using System.Collections.Generic;

namespace FlightStreamDeck.Core
{
    public static class EventValueLibrary
    {
        static List<ToggleValue> availableValues = new List<ToggleValue> {
            new ToggleValue("THROTTLE_LOWER_LIMIT", "Percent", 2),
            new ToggleValue("GENERAL_ENG_RPM__1", "Rpm", 1),
            new ToggleValue("GENERAL_ENG_RPM__2", "Rpm", 1),
            new ToggleValue("GENERAL_ENG_RPM__3", "Rpm", 1),
            new ToggleValue("GENERAL_ENG_RPM__4", "Rpm", 1),
            new ToggleValue("GENERAL_ENG_THROTTLE_LEVER_POSITION__1", "Percent", 2),
            new ToggleValue("GENERAL_ENG_THROTTLE_LEVER_POSITION__2", "Percent", 2),
            new ToggleValue("GENERAL_ENG_THROTTLE_LEVER_POSITION__3", "Percent", 2),
            new ToggleValue("GENERAL_ENG_THROTTLE_LEVER_POSITION__4", "Percent", 2),
            new ToggleValue("GENERAL_ENG_MIXTURE_LEVER_POSITION__1", "Percent", 2),
            new ToggleValue("GENERAL_ENG_MIXTURE_LEVER_POSITION__2", "Percent", 2),
            new ToggleValue("GENERAL_ENG_MIXTURE_LEVER_POSITION__3", "Percent", 2),
            new ToggleValue("GENERAL_ENG_MIXTURE_LEVER_POSITION__4", "Percent", 2),
            new ToggleValue("GENERAL_ENG_PROPELLER_LEVER_POSITION__1", "Percent", 2),
            new ToggleValue("GENERAL_ENG_PROPELLER_LEVER_POSITION__2", "Percent", 2),
            new ToggleValue("GENERAL_ENG_PROPELLER_LEVER_POSITION__3", "Percent", 2),
            new ToggleValue("GENERAL_ENG_PROPELLER_LEVER_POSITION__4", "Percent", 2),
            new ToggleValue("GENERAL_ENG_EXHAUST_GAS_TEMPERATURE__1", "Percent", 0),
            new ToggleValue("GENERAL_ENG_EXHAUST_GAS_TEMPERATURE__2", "Percent", 0),
            new ToggleValue("GENERAL_ENG_EXHAUST_GAS_TEMPERATURE__3", "Percent", 0),
            new ToggleValue("GENERAL_ENG_EXHAUST_GAS_TEMPERATURE__4", "Percent", 0),
            new ToggleValue("ENG_MAX_RPM", "Rpm", 1),
            new ToggleValue("GENERAL_ENG_FUEL_USED_SINCE_START", "Pounds", 2),
            new ToggleValue("TURB_ENG_ITT__1", "Celsius", 0),
            new ToggleValue("TURB_ENG_ITT__2", "Celsius", 0),
            new ToggleValue("TURB_ENG_ITT__3", "Celsius", 0),
            new ToggleValue("TURB_ENG_ITT__4", "Celsius", 0),
            new ToggleValue("TURB_ENG_AFTERBURNER_PCT_ACTIVE", "Percent", 0),
            new ToggleValue("ENG_FUEL_FLOW_GPH__1", "Gallons per hour", 0),
            new ToggleValue("ENG_FUEL_FLOW_GPH__2", "Gallons per hour", 0),
            new ToggleValue("ENG_FUEL_FLOW_GPH__3", "Gallons per hour", 0),
            new ToggleValue("ENG_FUEL_FLOW_GPH__4", "Gallons per hour", 0),
            new ToggleValue("FUEL_TANK_CENTER_LEVEL", "Percent", 0),
            new ToggleValue("FUEL_TANK_CENTER2_LEVEL", "Percent", 0),
            new ToggleValue("FUEL_TANK_CENTER3_LEVEL", "Percent", 0),
            new ToggleValue("FUEL_TANK_LEFT_MAIN_LEVEL", "Percent", 0),
            new ToggleValue("FUEL_TANK_LEFT_AUX_LEVEL", "Percent", 0),
            new ToggleValue("FUEL_TANK_LEFT_TIP_LEVEL", "Percent", 0),
            new ToggleValue("FUEL_TANK_RIGHT_MAIN_LEVEL", "Percent", 0),
            new ToggleValue("FUEL_TANK_RIGHT_AUX_LEVEL", "Percent", 0),
            new ToggleValue("FUEL_TANK_RIGHT_TIP_LEVEL", "Percent", 0),
            new ToggleValue("FUEL_TANK_EXTERNAL1_LEVEL", "Percent", 0),
            new ToggleValue("FUEL_TANK_EXTERNAL2_LEVEL", "Percent", 0),
            new ToggleValue("FUEL_TANK_CENTER_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_CENTER2_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_CENTER3_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_LEFT_MAIN_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_LEFT_AUX_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_LEFT_TIP_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_RIGHT_MAIN_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_RIGHT_AUX_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_RIGHT_TIP_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_EXTERNAL1_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_EXTERNAL2_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_LEFT_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_RIGHT_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_TOTAL_CAPACITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_CENTER_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_CENTER2_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_CENTER3_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_LEFT_MAIN_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_LEFT_AUX_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_LEFT_TIP_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_RIGHT_MAIN_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_RIGHT_AUX_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_RIGHT_TIP_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_EXTERNAL1_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_TANK_EXTERNAL2_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_LEFT_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_RIGHT_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_TOTAL_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_WEIGHT_PER_GALLON", "Pounds", 2),
            new ToggleValue("FUEL_SELECTED_QUANTITY_PERCENT", "Percent", 2),
            new ToggleValue("FUEL_SELECTED_QUANTITY", "Gallons", 2),
            new ToggleValue("FUEL_TOTAL_QUANTITY_WEIGHT", "Pounds", 2),
            new ToggleValue("ESTIMATED_FUEL_FLOW", "Pounds per hour", 2),
            new ToggleValue("GROUND_VELOCITY", "Knots", 2),
            new ToggleValue("TOTAL_WORLD_VELOCITY", "meter per second", 2),
            new ToggleValue("VELOCITY_BODY_Z", "meter per second", 0),
            new ToggleValue("VELOCITY_BODY_X", "meter per second", 0),
            new ToggleValue("VELOCITY_BODY_Y", "meter per second", 0),
            new ToggleValue("VELOCITY_WORLD_Z", "meter per second", 0),
            new ToggleValue("VELOCITY_WORLD_X", "meter per second", 0),
            new ToggleValue("VELOCITY_WORLD_Y", "meter per second", 0),
            new ToggleValue("ACCELERATION_WORLD_X", "meter per second squared", 2),
            new ToggleValue("ACCELERATION_WORLD_Y", "meter per second squared", 2),
            new ToggleValue("ACCELERATION_WORLD_Z", "meter per second squared", 2),
            new ToggleValue("ACCELERATION_BODY_X", "meter per second squared", 2),
            new ToggleValue("ACCELERATION_BODY_Y", "meter per second squared", 2),
            new ToggleValue("ACCELERATION_BODY_Z", "meter per second squared", 2),
            new ToggleValue("ROTATION_VELOCITY_BODY_X", "meter per second", 2),
            new ToggleValue("ROTATION_VELOCITY_BODY_Y", "meter per second", 2),
            new ToggleValue("ROTATION_VELOCITY_BODY_Z", "meter per second", 2),
            new ToggleValue("RELATIVE_WIND_VELOCITY_BODY_X", "meter per second", 2),
            new ToggleValue("ROTATION_VELOCITY_BODY_Y", "meter per second", 2),
            new ToggleValue("ROTATION_VELOCITY_BODY_Z", "meter per second", 2),
            new ToggleValue("PLANE_ALT_ABOVE_GROUND", "Feet", 2),
            new ToggleValue("PLANE_ALTITUDE", "Feet", 2),
            new ToggleValue("MAGVAR", "Degrees", 0),
            new ToggleValue("GROUND_ALTITUDE", "Meters", 2),
            new ToggleValue("AIRSPEED_TRUE", "Knots", 0),
            new ToggleValue("AIRSPEED_INDICATED", "Knots", 0),
            new ToggleValue("AIRSPEED_TRUE_CALIBRATE", "Degrees", 0),
            new ToggleValue("AIRSPEED_BARBER_POLE", "Knots", 0),
            new ToggleValue("AIRSPEED_MACH", "Mach", 2),
            new ToggleValue("AIRSPEED_MACH", "Feet per minute", 0),
            new ToggleValue("MACH_MAX_OPERATE", "Mach", 2),
            new ToggleValue("BARBER_POLE_MACH", "Mach", 2),
            new ToggleValue("INDICATED_ALTITUDE", "Feet", 0),
            new ToggleValue("KOHLSMAN_SETTING_MB", "Millibars", 0),
            new ToggleValue("KOHLSMAN_SETTING_HG", "inHg", 2),
            new ToggleValue("ATTITUDE_BARS_POSITION", "Percent", 0),
            new ToggleValue("WISKEY_COMPASS_INDICATION_DEGREES", "Degrees", 0),
            new ToggleValue("RADIO_HEIGHT", "Feet", 0),
            new ToggleValue("MAX_G_FORCE", "Gforce", 2),
            new ToggleValue("MIN_G_FORCE", "Gforce", 2),
            new ToggleValue("SUCTION_PRESSURE", "inHg", 2),
            new ToggleValue("ADF_CARD", "Degrees", 0),
            new ToggleValue("HSI_BEARING", "Degrees", 0),
            new ToggleValue("HSI_SPEED", "Knots", 0),
            new ToggleValue("HSI_DISTANCE", "Nautical miles", 2),
            new ToggleValue("GPS_POSITION_LAT", "Degrees", 10),
            new ToggleValue("GPS_POSITION_LON", "Degrees", 10),
            new ToggleValue("GPS_POSITION_ALT", "Meters", 2),
            new ToggleValue("GPS_GROUND_SPEED", "Meters per second", 2),
            new ToggleValue("GPS_WP_DISTANCE", "Meters", 2),
            new ToggleValue("GPS_WP_CROSS_TRK", "Meters", 2),
            new ToggleValue("GPS_WP_VERTICAL_SPEED", "Meters per second", 2),
            new ToggleValue("GPS_ETE", "Seconds", 0),
            new ToggleValue("GPS_ETA", "Seconds", 0),
            new ToggleValue("GPS_WP_NEXT_LAT", "Degrees", 10),
            new ToggleValue("GPS_WP_NEXT_LON", "Degrees", 10),
            new ToggleValue("GPS_WP_NEXT_ALT", "Meters", 0),
            new ToggleValue("GPS_WP_PREV_LAT", "Degrees", 10),
            new ToggleValue("GPS_WP_PREV_LON", "Degrees", 10),
            new ToggleValue("GPS_WP_PREV_ALT", "Meters", 0),
            new ToggleValue("GPS_WP_ETE", "Seconds", 0),
            new ToggleValue("GPS_WP_ETA", "Seconds", 0),
            new ToggleValue("GPS_APPROACH_TIMEZONE_DEVIATION", "Seconds", 0),
            new ToggleValue("GPS_TARGET_DISTANCE", "Meters", 2),
            new ToggleValue("GPS_TARGET_ALTITUDE", "Meters", 2),
            new ToggleValue("ELEVATOR_TRIM_POSITION", "Radians", 2),
            new ToggleValue("ELEVATOR_TRIM_PCT", "Percent", 0),
            new ToggleValue("SPOILERS_HANDLE_POSITION", "Position", 2),
            new ToggleValue("SPOILERS_LEFT_POSITION", "Position", 2),
            new ToggleValue("SPOILERS_RIGHT_POSITION", "Position", 2),
            new ToggleValue("FLAPS_HANDLE_PERCENT", "Percent", 0),
            new ToggleValue("TRAILING_EDGE_FLAPS_LEFT_PERCENT", "Percent", 0),
            new ToggleValue("TRAILING_EDGE_FLAPS_RIGHT_PERCENT", "Percent", 0),
            new ToggleValue("LEADING_EDGE_FLAPS_LEFT_PERCENT", "Percent", 0),
            new ToggleValue("LEADING_EDGE_FLAPS_RIGHT_PERCENT", "Percent", 0),
            new ToggleValue("AILERON_LEFT_DEFLECTION_PCT", "Percent", 0),
            new ToggleValue("AILERON_RIGHT_DEFLECTION_PCT", "Percent", 0),
            new ToggleValue("AILERON_TRIM", "Radians", 2),
            new ToggleValue("AILERON_TRIM_PCT", "Percent", 0),
            new ToggleValue("RUDDER_DEFLECTION_PCT", "Percent", 0),
            new ToggleValue("RUDDER_TRIM_PCT", "Percent", 0),
            new ToggleValue("ELEVATOR_DEFLECTION_PCT", "Percent", 0),
            new ToggleValue("AUTOPILOT_HEADING_LOCK_DIR", "Degrees", 0),
            new ToggleValue("AUTOPILOT_HEADING_LOCK_DIR__1", "Degrees", 0),
            new ToggleValue("AUTOPILOT_ALTITUDE_LOCK_VAR", "Feet", 0),
            new ToggleValue("AUTOPILOT_ALTITUDE_LOCK_VAR__1", "Feet", 0),
            new ToggleValue("AUTOPILOT_ALTITUDE_LOCK_VAR__2", "Feet", 0),
            new ToggleValue("AUTOPILOT_ALTITUDE_LOCK_VAR__3", "Feet", 0),
            new ToggleValue("AUTOPILOT_VERTICAL_HOLD_VAR", "Feet/minute", 0),
            new ToggleValue("AUTOPILOT_VERTICAL_HOLD_VAR__1", "Feet/minute", 0),
            new ToggleValue("AUTOPILOT_VERTICAL_HOLD_VAR__2", "Feet/minute", 0),
            new ToggleValue("AUTOPILOT_VERTICAL_HOLD_VAR__3", "Feet/minute", 0),
            new ToggleValue("AUTOPILOT_AIRSPEED_HOLD_VAR", "Knots", 0),
            new ToggleValue("AUTOPILOT_AIRSPEED_HOLD_VAR__1", "Knots", 0),
            new ToggleValue("AUTOPILOT_AIRSPEED_HOLD_VAR__2", "Knots", 0),
            new ToggleValue("GEAR_HYDRAULIC_PRESSURE", "Pound force per square foot (psf)", 2),
            new ToggleValue("GEAR_CENTER_POSITION", "Percent", 0),
            new ToggleValue("GEAR_LEFT_POSITION", "Percent", 0),
            new ToggleValue("GEAR_RIGHT_POSITION", "Percent", 0),
            new ToggleValue("GEAR_TAIL_POSITION", "Percent", 0),
            new ToggleValue("GEAR_AUX_POSITION", "Percent", 0),
            new ToggleValue("GEAR_TOTAL_PCT_EXTENDED", "Percent", 0),
            new ToggleValue("WATER_RUDDER_HANDLE_POSITION", "Percent", 0),
            new ToggleValue("WATER_LEFT_RUDDER_EXTENDED", "Percentage", 0),
            new ToggleValue("WATER_RIGHT_RUDDER_EXTENDED", "Percentage", 0),
            new ToggleValue("GEAR_CENTER_STEER_ANGLE", "Percent", 0),
            new ToggleValue("GEAR_LEFT_STEER_ANGLE", "Percent", 0),
            new ToggleValue("GEAR_RIGHT_STEER_ANGLE", "Percent", 0),
            new ToggleValue("GEAR_AUX_STEER_ANGLE", "Percent", 0),
            new ToggleValue("WATER_LEFT_RUDDER_STEER_ANGLE", "Percent", 0),
            new ToggleValue("WATER_RIGHT_RUDDER_STEER_ANGLE", "Percent", 0),
            new ToggleValue("GEAR_CENTER_STEER_ANGLE_PCT", "Percent", 0),
            new ToggleValue("GEAR_LEFT_STEER_ANGLE_PCT", "Percent", 0),
            new ToggleValue("GEAR_RIGHT_STEER_ANGLE_PCT", "Percent", 0),
            new ToggleValue("GEAR_AUX_STEER_ANGLE_PCT", "Percent", 0),
            new ToggleValue("WATER_LEFT_RUDDER_STEER_ANGLE_PCT", "Percent", 0),
            new ToggleValue("WATER_RIGHT_RUDDER_STEER_ANGLE_PCT", "Percent", 0),
            new ToggleValue("CENTER_WHEEL_RPM", "Rpm", 0),
            new ToggleValue("LEFT_WHEEL_RPM", "Rpm", 0),
            new ToggleValue("RIGHT_WHEEL_RPM", "Rpm", 0),
            new ToggleValue("AUX_WHEEL_RPM", "Rpm", 0),
            new ToggleValue("RETRACT_LEFT_FLOAT_EXTENDED", "Percent", 0),
            new ToggleValue("RETRACT_RIGHT_FLOAT_EXTENDED", "Percent", 0),
            new ToggleValue("STEER_INPUT_CONTROL", "Percent", 0),
            new ToggleValue("AMBIENT_DENSITY", "Slugs per cubic feet", 0),
            new ToggleValue("AMBIENT_TEMPERATURE", "Celsius", 2),
            new ToggleValue("AMBIENT_PRESSURE", "inHg", 2),
            new ToggleValue("AMBIENT_WIND_VELOCITY", "Knots", 0),
            new ToggleValue("AMBIENT_WIND_DIRECTION", "Degrees", 0),
            new ToggleValue("AMBIENT_WIND_X", "Meters per second", 0),
            new ToggleValue("AMBIENT_WIND_Y", "Meters per second", 0),
            new ToggleValue("AMBIENT_WIND_Z", "Meters per second", 0),
            new ToggleValue("STRUCT_AMBIENT_WIND", "Feet_per_second", 0),
            new ToggleValue("AIRCRAFT_WIND_X", "Knots", 0),
            new ToggleValue("AIRCRAFT_WIND_Y", "Knots", 0),
            new ToggleValue("AIRCRAFT_WIND_Z", "Knots", 0),
            new ToggleValue("BAROMETER_PRESSURE", "Millibars", 0),
            new ToggleValue("SEA_LEVEL_PRESSURE", "Millibars", 0),
            new ToggleValue("TOTAL_AIR_TEMPERATURE", "Celsius", 2),
            new ToggleValue("AMBIENT_VISIBILITY", "Meters", 0),
            new ToggleValue("STANDARD_ATM_TEMPERATURE", "Celsius", 0),
            new ToggleValue("FOLDING_WING_LEFT_PERCENT", "Percent", 0),
            new ToggleValue("FOLDING_WING_RIGHT_PERCENT", "Percent", 0),
            new ToggleValue("CANOPY_OPEN", "Percent", 0),
            new ToggleValue("TAILHOOK_POSITION", "Percent", 0),
            new ToggleValue("ELECTRICAL_TOTAL_LOAD_AMPS", "Amperes", 2),
            new ToggleValue("ELECTRICAL_BATTERY_LOAD", "Amperes", 2),
            new ToggleValue("ELECTRICAL_BATTERY_VOLTAGE", "Volts", 2),
            new ToggleValue("ELECTRICAL_MAIN_BUS_VOLTAGE", "Volts", 2),
            new ToggleValue("ELECTRICAL_MAIN_BUS_AMPS", "Amperes", 2),
            new ToggleValue("ELECTRICAL_AVIONICS_BUS_VOLTAGE", "Volts", 2),
            new ToggleValue("ELECTRICAL_AVIONICS_BUS_AMPS", "Amperes", 2),
            new ToggleValue("ELECTRICAL_HOT_BATTERY_BUS_VOLTAGE", "Volts", 2),
            new ToggleValue("ELECTRICAL_HOT_BATTERY_BUS_AMPS", "Amperes", 2),
            new ToggleValue("ELECTRICAL_BATTERY_BUS_VOLTAGE", "Volts", 2),
            new ToggleValue("ELECTRICAL_BATTERY_BUS_AMPS", "Amperes", 2),
            new ToggleValue("ELECTRICAL_BATTERY_BUS_CONTACT_SWITCH", "Volts", 2),
            new ToggleValue("HYDRAULIC_SYSTEM_INTEGRITY", "Percent", 0),
            new ToggleValue("TOTAL_WEIGHT", "Pounds", 0),
            new ToggleValue("MAX_GROSS_WEIGHT", "Pounds", 0),
            new ToggleValue("EMPTY_WEIGHT", "Pounds", 0),
            new ToggleValue("EMPTY_WEIGHT", "GForce", 2),
            new ToggleValue("DESIGN_SPEED_VS0", "Feet per second", 0),
            new ToggleValue("DESIGN_SPEED_VS1", "Feet per second", 0),
            new ToggleValue("DESIGN_SPEED_VC", "Feet per second", 0),
            new ToggleValue("MIN_DRAG_VELOCITY", "Feet per second", 0),
            new ToggleValue("ESTIMATED_CRUISE_SPEED", "Feet per second", 0),
            new ToggleValue("CG_PERCENT", "Percent", 0),
            new ToggleValue("CG_PERCENT_LATERAL", "Percent", 0),
            new ToggleValue("ATC_SUGGESTED_MIN_RWY_TAKEOFF", "Feet", 0),
            new ToggleValue("ATC_SUGGESTED_MIN_RWY_LANDING", "Feet", 0),
            new ToggleValue("TYPICAL_DESCENT_RATE", "Feet per minute", 0),
            new ToggleValue("VISUAL_MODEL_RADIUS", "Meters", 2),
            new ToggleValue("DYNAMIC_PRESSURE", "Pounds per square foot", 0),
            new ToggleValue("TOTAL_VELOCITY", "Feet per second", 0),
            new ToggleValue("AIRSPEED_SELECT_INDICATED_OR_TRUE", "Knots", 0),
            new ToggleValue("VARIOMETER_RATE", "Feet per second", 0),
            new ToggleValue("PRESSURE_ALTITUDE", "Meters", 0),
            new ToggleValue("MAGNETIC_COMPASS", "Degrees", 0),
            new ToggleValue("BRAKE_DEPENDENT_HYDRAULIC_PRESSURE", "Pounds per square foot", 2),
            new ToggleValue("WING_AREA", "Square feet", 2),
            new ToggleValue("WING_SPAN", "Feet", 2),
            new ToggleValue("LINEAR_CL_ALPHA", "Per radian", 2),
            new ToggleValue("CG_AFT_LIMIT", "Percent", 0),
            new ToggleValue("CG_FWD_LIMIT", "Percent", 0),
            new ToggleValue("CG_MAX_MACH", "Machs", 2),
            new ToggleValue("CG_MIN_MACH", "Machs", 2),
            new ToggleValue("EXIT_POSX", "Feet", 2),
            new ToggleValue("EXIT_POSY", "Feet", 2),
            new ToggleValue("EXIT_POSY", "Feet", 2),
            new ToggleValue("DECISION_HEIGHT", "Feet", 0),
            new ToggleValue("DECISION_ALTITUDE_MSL", "Feet", 0),
            new ToggleValue("EMPTY_WEIGHT_PITCH_MOI", "Slugs per feet squared", 2),
            new ToggleValue("EMPTY_WEIGHT_ROLL_MOI", "Slugs per feet squared", 2),
            new ToggleValue("EMPTY_WEIGHT_YAW_MOI", "Slugs per feet squared", 2),
            new ToggleValue("EMPTY_WEIGHT_CROSS_COUPLED_MOI", "Slugs per feet squared", 2),
            new ToggleValue("TOTAL_WEIGHT_PITCH_MOI", "Slugs per feet squared", 2),
            new ToggleValue("TOTAL_WEIGHT_ROLL_MOI", "Slugs per feet squared", 2),
            new ToggleValue("TOTAL_WEIGHT_YAW_MOI", "Slugs per feet squared", 2),
            new ToggleValue("TOTAL_WEIGHT_CROSS_COUPLED_MOI", "Slugs per feet squared", 2),
            new ToggleValue("MAX_RATED_ENGINE_RPM", "Rpm", 0),
            new ToggleValue("MANUAL_FUEL_PUMP_HANDLE", "Percent", 0),
            new ToggleValue("ELECTRICAL_OLD_CHARGING_AMPS", "Amps", 2),
            new ToggleValue("CONCORDE_VISOR_POSITION_PERCENT", "Percent", 0),
            new ToggleValue("PITOT_ICE_PCT", "Percent", 0),
            new ToggleValue("SIMULATED_RADIUS", "Feet", 0),
            new ToggleValue("STRUCTURAL_ICE_PCT", "Percent", 0),
            new ToggleValue("ARTIFICIAL_GROUND_ELEVATION", "Feet", 0),
            new ToggleValue("PUSHBACK_CONTACTX", "Feet", 0),
            new ToggleValue("PUSHBACK_CONTACTY", "Feet", 0),
            new ToggleValue("PUSHBACK_CONTACTZ", "Feet", 0),
            new ToggleValue("YAW_STRING_PCT_EXTENDED", "Percent", 0),
            new ToggleValue("INDUCTOR_COMPASS_PERCENT_DEVIATION", "Percent", 0),
            new ToggleValue("ANEMOMETER_PCT_RPM", "Percent", 0),
            new ToggleValue("NAV_VOR_LLAF64", "LLA structure", 0),
            new ToggleValue("NAV_GS_LLAF64", "LLA structure", 0),
            new ToggleValue("STATIC_CG_TO_GROUND", "Feet", 2),
            new ToggleValue("TOW_RELEASE_HANDLE", "Percent", 0),
            new ToggleValue("APU_PCT_RPM", "Percent", 0),
            new ToggleValue("APU_PCT_STARTER", "Percent", 0),
            new ToggleValue("APU_VOLTS", "Volts", 2),
            new ToggleValue("PRESSURIZATION_CABIN_ALTITUDE", "Feet", 0),
            new ToggleValue("PRESSURIZATION_CABIN_ALTITUDE_GOAL", "Feet", 0),
            new ToggleValue("PRESSURIZATION_CABIN_ALTITUDE_RATE", "Feet per second", 0),
            new ToggleValue("PRESSURIZATION_PRESSURE_DIFFERENTIAL", "Pounds per square foot", 0),
            new ToggleValue("NAV_ACTIVE_FREQUENCY__1", "MHz", 2),
            new ToggleValue("NAV_STANDBY_FREQUENCY__1", "MHz", 2),
            new ToggleValue("NAV_ACTIVE_FREQUENCY__2", "MHz", 2),
            new ToggleValue("NAV_STANDBY_FREQUENCY__2", "MHz", 2),
            new ToggleValue("COM_ACTIVE_FREQUENCY__1", "MHz", 3),
            new ToggleValue("COM_STANDBY_FREQUENCY__1", "MHz", 3),
            new ToggleValue("COM_ACTIVE_FREQUENCY__2", "MHz", 3),
            new ToggleValue("COM_STANDBY_FREQUENCY__2", "MHz", 3),
            new ToggleValue("ADF_ACTIVE_FREQUENCY__1", "MHz", 0),
            new ToggleValue("ADF_STANDBY_FREQUENCY__1", "MHz", 0),
            new ToggleValue("ADF_ACTIVE_FREQUENCY__2", "MHz", 0),
            new ToggleValue("ADF_STANDBY_FREQUENCY__2", "MHz", 0),
            new ToggleValue("PLANE_PITCH_DEGREES", "Degrees", 2),
            new ToggleValue("PLANE_BANK_DEGREES", "Degrees", 2),
            new ToggleValue("PLANE_HEADING_DEGREES_TRUE", "Degrees", 2),
            new ToggleValue("PLANE_HEADING_DEGREES_MAGNETIC", "Degrees", 2),
            new ToggleValue("TURB_ENG_MAX_TORQUE_PERCENT__1", "Percent", 0),
            new ToggleValue("TURB_ENG_MAX_TORQUE_PERCENT__2", "Percent", 0),
            new ToggleValue("GENERAL_ENG_PCT_MAX_RPM__1", "Percent", 0),
            new ToggleValue("GENERAL_ENG_PCT_MAX_RPM__2", "Percent", 0),
            new ToggleValue("TURB_ENG_PRIMARY_NOZZLE_PERCENT__1", "Percent", 0),
            new ToggleValue("TURB_ENG_PRIMARY_NOZZLE_PERCENT__2", "Percent", 0),
            new ToggleValue("NAV_OBS__1", "Degrees", 0),
            new ToggleValue("NAV_OBS__2", "Degrees", 0),
            new ToggleValue("NAV_DME__1", "Nautical miles", 1),
            new ToggleValue("NAV_DME__2", "Nautical miles", 1),
            new ToggleValue("NAV_DMESPEED__1", "Knots", 0),
            new ToggleValue("NAV_DMESPEED__2", "Knots", 0),
            new ToggleValue("RECIP_ENG_COWL_FLAP_POSITION__1", "Percent", 2),
            new ToggleValue("TURN_COORDINATOR_BALL", "Position 128", 0),
            new ToggleValue("RECIP_ENG_MANIFOLD_PRESSURE__1", "Psi", 0),
            new ToggleValue("RECIP_ENG_MANIFOLD_PRESSURE__2", "Psi", 0),
            new ToggleValue("RECIP_ENG_MANIFOLD_PRESSURE__3", "Psi", 0),
            new ToggleValue("RECIP_ENG_MANIFOLD_PRESSURE__4", "Psi", 0),
            new ToggleValue("TURB_ENG_JET_THRUST__1", "Pounds", 2),
            new ToggleValue("TURB_ENG_JET_THRUST__2", "Pounds", 2),
            new ToggleValue("TURB_ENG_JET_THRUST__3", "Pounds", 2),
            new ToggleValue("TURB_ENG_JET_THRUST__4", "Pounds", 2),
            new ToggleValue("PROP_THRUST__1", "Pounds", 2),
            new ToggleValue("PROP_THRUST__2", "Pounds", 2),
            new ToggleValue("PROP_THRUST__3", "Pounds", 2),
            new ToggleValue("PROP_THRUST__4", "Pounds", 2),
            new ToggleValue("PROP_RPM__1", "Rpm", 1),
            new ToggleValue("PROP_RPM__2", "Rpm", 1),
            new ToggleValue("PROP_RPM__3", "Rpm", 1),
            new ToggleValue("PROP_RPM__4", "Rpm", 1),
            new ToggleValue("ENG_CYLINDER_HEAD_TEMPERATURE__1", "Celsius", 0),
            new ToggleValue("ENG_CYLINDER_HEAD_TEMPERATURE__2", "Celsius", 0),
            new ToggleValue("ENG_CYLINDER_HEAD_TEMPERATURE__3", "Celsius", 0),
            new ToggleValue("ENG_CYLINDER_HEAD_TEMPERATURE__4", "Celsius", 0),
            new ToggleValue("RECIP_ENG_CYLINDER_HEAD_TEMPERATURE__1", "Celsius", 0),
            new ToggleValue("RECIP_ENG_CYLINDER_HEAD_TEMPERATURE__2", "Celsius", 0),
            new ToggleValue("RECIP_ENG_CYLINDER_HEAD_TEMPERATURE__3", "Celsius", 0),
            new ToggleValue("RECIP_ENG_CYLINDER_HEAD_TEMPERATURE__4", "Celsius", 0),
            new ToggleValue("ENG_OIL_TEMPERATURE__1", "Celsius", 0),
            new ToggleValue("ENG_OIL_TEMPERATURE__2", "Celsius", 0),
            new ToggleValue("ENG_OIL_TEMPERATURE__3", "Celsius", 0),
            new ToggleValue("ENG_OIL_TEMPERATURE__4", "Celsius", 0),
            new ToggleValue("GENERAL_ENG_OIL_TEMPERATURE__1", "Celsius", 0),
            new ToggleValue("GENERAL_ENG_OIL_TEMPERATURE__2", "Celsius", 0),
            new ToggleValue("GENERAL_ENG_OIL_TEMPERATURE__3", "Celsius", 0),
            new ToggleValue("GENERAL_ENG_OIL_TEMPERATURE__4", "Celsius", 0),

        };
    }
}