using System.Collections.Generic;

namespace FlightStreamDeck.Core
{
    public static class EventValueLibrary
    {
        struct ValueEntry
        {
            public ValueEntry(string unit, short decimals)
            {
                Unit = unit;
                Decimals = decimals;
            }

            public string Unit;
            public int Decimals;
        }

        const string DEFAULT_UNIT = "number";
        const int DEFAULT_DECIMALS = 0;

        static Dictionary<TOGGLE_VALUE, ValueEntry> availableValues = new Dictionary<TOGGLE_VALUE, ValueEntry>()
        {
            { TOGGLE_VALUE.THROTTLE_LOWER_LIMIT, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.GENERAL_ENG_RPM__1, new ValueEntry("Rpm", 1) },
            { TOGGLE_VALUE.GENERAL_ENG_RPM__2, new ValueEntry("Rpm", 1) },
            { TOGGLE_VALUE.GENERAL_ENG_RPM__3, new ValueEntry("Rpm", 1) },
            { TOGGLE_VALUE.GENERAL_ENG_RPM__4, new ValueEntry("Rpm", 1) },
            { TOGGLE_VALUE.GENERAL_ENG_THROTTLE_LEVER_POSITION__1, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.GENERAL_ENG_THROTTLE_LEVER_POSITION__2, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.GENERAL_ENG_THROTTLE_LEVER_POSITION__3, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.GENERAL_ENG_THROTTLE_LEVER_POSITION__4, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.GENERAL_ENG_MIXTURE_LEVER_POSITION__1, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.GENERAL_ENG_MIXTURE_LEVER_POSITION__2, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.GENERAL_ENG_MIXTURE_LEVER_POSITION__3, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.GENERAL_ENG_MIXTURE_LEVER_POSITION__4, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.GENERAL_ENG_PROPELLER_LEVER_POSITION__1, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.GENERAL_ENG_PROPELLER_LEVER_POSITION__2, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.GENERAL_ENG_PROPELLER_LEVER_POSITION__3, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.GENERAL_ENG_PROPELLER_LEVER_POSITION__4, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.GENERAL_ENG_EXHAUST_GAS_TEMPERATURE__1, new ValueEntry("Celsius", 0) },
            { TOGGLE_VALUE.GENERAL_ENG_EXHAUST_GAS_TEMPERATURE__2, new ValueEntry("Celsius", 0) },
            { TOGGLE_VALUE.GENERAL_ENG_EXHAUST_GAS_TEMPERATURE__3, new ValueEntry("Celsius", 0) },
            { TOGGLE_VALUE.GENERAL_ENG_EXHAUST_GAS_TEMPERATURE__4, new ValueEntry("Celsius", 0) },
            { TOGGLE_VALUE.ENG_MAX_RPM, new ValueEntry("Rpm", 1) },
            { TOGGLE_VALUE.GENERAL_ENG_FUEL_USED_SINCE_START, new ValueEntry("Pounds", 2) },
            { TOGGLE_VALUE.TURB_ENG_ITT__1, new ValueEntry("Celsius", 0) },
            { TOGGLE_VALUE.TURB_ENG_ITT__2, new ValueEntry("Celsius", 0) },
            { TOGGLE_VALUE.TURB_ENG_ITT__3, new ValueEntry("Celsius", 0) },
            { TOGGLE_VALUE.TURB_ENG_ITT__4, new ValueEntry("Celsius", 0) },
            { TOGGLE_VALUE.TURB_ENG_AFTERBURNER_PCT_ACTIVE, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.ENG_FUEL_FLOW_GPH__1, new ValueEntry("Gallons per hour", 0) },
            { TOGGLE_VALUE.ENG_FUEL_FLOW_GPH__2, new ValueEntry("Gallons per hour", 0) },
            { TOGGLE_VALUE.ENG_FUEL_FLOW_GPH__3, new ValueEntry("Gallons per hour", 0) },
            { TOGGLE_VALUE.ENG_FUEL_FLOW_GPH__4, new ValueEntry("Gallons per hour", 0) },
            { TOGGLE_VALUE.FUEL_TANK_CENTER_LEVEL, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.FUEL_TANK_CENTER2_LEVEL, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.FUEL_TANK_CENTER3_LEVEL, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.FUEL_TANK_LEFT_MAIN_LEVEL, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.FUEL_TANK_LEFT_AUX_LEVEL, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.FUEL_TANK_LEFT_TIP_LEVEL, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.FUEL_TANK_RIGHT_MAIN_LEVEL, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.FUEL_TANK_RIGHT_AUX_LEVEL, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.FUEL_TANK_RIGHT_TIP_LEVEL, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.FUEL_TANK_EXTERNAL1_LEVEL, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.FUEL_TANK_EXTERNAL2_LEVEL, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.FUEL_TANK_CENTER_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_CENTER2_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_CENTER3_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_LEFT_MAIN_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_LEFT_AUX_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_LEFT_TIP_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_RIGHT_MAIN_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_RIGHT_AUX_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_RIGHT_TIP_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_EXTERNAL1_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_EXTERNAL2_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_LEFT_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_RIGHT_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_CENTER_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_CENTER2_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_CENTER3_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_LEFT_MAIN_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_LEFT_AUX_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_LEFT_TIP_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_RIGHT_MAIN_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_RIGHT_AUX_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_RIGHT_TIP_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_EXTERNAL1_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TANK_EXTERNAL2_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_LEFT_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_RIGHT_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TOTAL_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_WEIGHT_PER_GALLON, new ValueEntry("Pounds", 2) },
            { TOGGLE_VALUE.FUEL_TOTAL_CAPACITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_SELECTED_QUANTITY_PERCENT, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.FUEL_SELECTED_QUANTITY, new ValueEntry("Gallons", 2) },
            { TOGGLE_VALUE.FUEL_TOTAL_QUANTITY_WEIGHT, new ValueEntry("Pounds", 2) },
            { TOGGLE_VALUE.ESTIMATED_FUEL_FLOW, new ValueEntry("Pounds per hour", 2) },
            { TOGGLE_VALUE.GROUND_VELOCITY, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.TOTAL_WORLD_VELOCITY, new ValueEntry("meter per second", 2) },
            { TOGGLE_VALUE.VELOCITY_BODY_Z, new ValueEntry("meter per second", 0) },
            { TOGGLE_VALUE.VELOCITY_BODY_X, new ValueEntry("meter per second", 0) },
            { TOGGLE_VALUE.VELOCITY_BODY_Y, new ValueEntry("meter per second", 0) },
            { TOGGLE_VALUE.VELOCITY_WORLD_Z, new ValueEntry("meter per second", 0) },
            { TOGGLE_VALUE.VELOCITY_WORLD_X, new ValueEntry("meter per second", 0) },
            { TOGGLE_VALUE.VELOCITY_WORLD_Y, new ValueEntry("meter per second", 0) },
            { TOGGLE_VALUE.ACCELERATION_WORLD_X, new ValueEntry("meter per second squared", 2) },
            { TOGGLE_VALUE.ACCELERATION_WORLD_Y, new ValueEntry("meter per second squared", 2) },
            { TOGGLE_VALUE.ACCELERATION_WORLD_Z, new ValueEntry("meter per second squared", 2) },
            { TOGGLE_VALUE.ACCELERATION_BODY_X, new ValueEntry("meter per second squared", 2) },
            { TOGGLE_VALUE.ACCELERATION_BODY_Y, new ValueEntry("meter per second squared", 2) },
            { TOGGLE_VALUE.ACCELERATION_BODY_Z, new ValueEntry("meter per second squared", 2) },
            { TOGGLE_VALUE.ROTATION_VELOCITY_BODY_X, new ValueEntry("meter per second", 2) },
            { TOGGLE_VALUE.ROTATION_VELOCITY_BODY_Y, new ValueEntry("meter per second", 2) },
            { TOGGLE_VALUE.ROTATION_VELOCITY_BODY_Z, new ValueEntry("meter per second", 2) },
            { TOGGLE_VALUE.RELATIVE_WIND_VELOCITY_BODY_X, new ValueEntry("meter per second", 2) },
            { TOGGLE_VALUE.RELATIVE_WIND_VELOCITY_BODY_Y, new ValueEntry("meter per second", 2) },
            { TOGGLE_VALUE.RELATIVE_WIND_VELOCITY_BODY_Z, new ValueEntry("meter per second", 2) },
            { TOGGLE_VALUE.PLANE_ALT_ABOVE_GROUND, new ValueEntry("Feet", 2) },
            { TOGGLE_VALUE.PLANE_ALTITUDE, new ValueEntry("Feet", 2) },
            { TOGGLE_VALUE.MAGVAR, new ValueEntry("Degrees", 0) },
            { TOGGLE_VALUE.GROUND_ALTITUDE, new ValueEntry("Meters", 2) },
            { TOGGLE_VALUE.AIRSPEED_TRUE, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.AIRSPEED_INDICATED, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.AIRSPEED_TRUE_CALIBRATE, new ValueEntry("Degrees", 0) },
            { TOGGLE_VALUE.AIRSPEED_BARBER_POLE, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.AIRSPEED_MACH, new ValueEntry("Mach", 2) },
            { TOGGLE_VALUE.VERTICAL_SPEED, new ValueEntry("Feet per minute", 0) },
            { TOGGLE_VALUE.MACH_MAX_OPERATE, new ValueEntry("Mach", 2) },
            { TOGGLE_VALUE.BARBER_POLE_MACH, new ValueEntry("Mach", 2) },
            { TOGGLE_VALUE.INDICATED_ALTITUDE, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.KOHLSMAN_SETTING_MB, new ValueEntry("Millibars", 0) },
            { TOGGLE_VALUE.KOHLSMAN_SETTING_HG, new ValueEntry("inHg", 2) },
            { TOGGLE_VALUE.ATTITUDE_BARS_POSITION, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.WISKEY_COMPASS_INDICATION_DEGREES, new ValueEntry("Degrees", 0) },
            { TOGGLE_VALUE.RADIO_HEIGHT, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.MAX_G_FORCE, new ValueEntry("Gforce", 2) },
            { TOGGLE_VALUE.MIN_G_FORCE, new ValueEntry("Gforce", 2) },
            { TOGGLE_VALUE.SUCTION_PRESSURE, new ValueEntry("inHg", 2) },
            { TOGGLE_VALUE.ADF_CARD, new ValueEntry("Degrees", 0) },
            { TOGGLE_VALUE.HSI_BEARING, new ValueEntry("Degrees", 0) },
            { TOGGLE_VALUE.HSI_SPEED, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.HSI_DISTANCE, new ValueEntry("Nautical miles", 2) },
            { TOGGLE_VALUE.GPS_POSITION_LAT, new ValueEntry("Degrees", 10) },
            { TOGGLE_VALUE.GPS_POSITION_LON, new ValueEntry("Degrees", 10) },
            { TOGGLE_VALUE.GPS_POSITION_ALT, new ValueEntry("Meters", 2) },
            { TOGGLE_VALUE.GPS_GROUND_SPEED, new ValueEntry("Meters per second", 2) },
            { TOGGLE_VALUE.GPS_WP_DISTANCE, new ValueEntry("Meters", 2) },
            { TOGGLE_VALUE.GPS_WP_CROSS_TRK, new ValueEntry("Meters", 2) },
            { TOGGLE_VALUE.GPS_WP_VERTICAL_SPEED, new ValueEntry("Meters per second", 2) },
            { TOGGLE_VALUE.GPS_ETE, new ValueEntry("Seconds", 0) },
            { TOGGLE_VALUE.GPS_ETA, new ValueEntry("Seconds", 0) },
            { TOGGLE_VALUE.GPS_WP_NEXT_LAT, new ValueEntry("Degrees", 10) },
            { TOGGLE_VALUE.GPS_WP_NEXT_LON, new ValueEntry("Degrees", 10) },
            { TOGGLE_VALUE.GPS_WP_NEXT_ALT, new ValueEntry("Meters", 0) },
            { TOGGLE_VALUE.GPS_WP_PREV_LAT, new ValueEntry("Degrees", 10) },
            { TOGGLE_VALUE.GPS_WP_PREV_LON, new ValueEntry("Degrees", 10) },
            { TOGGLE_VALUE.GPS_WP_PREV_ALT, new ValueEntry("Meters", 0) },
            { TOGGLE_VALUE.GPS_WP_ETE, new ValueEntry("Seconds", 0) },
            { TOGGLE_VALUE.GPS_WP_ETA, new ValueEntry("Seconds", 0) },
            { TOGGLE_VALUE.GPS_APPROACH_TIMEZONE_DEVIATION, new ValueEntry("Seconds", 0) },
            { TOGGLE_VALUE.GPS_TARGET_DISTANCE, new ValueEntry("Meters", 2) },
            { TOGGLE_VALUE.GPS_TARGET_ALTITUDE, new ValueEntry("Meters", 2) },
            { TOGGLE_VALUE.ELEVATOR_TRIM_POSITION, new ValueEntry("Radians", 2) },
            { TOGGLE_VALUE.ELEVATOR_TRIM_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.SPOILERS_HANDLE_POSITION, new ValueEntry("Position", 2) },
            { TOGGLE_VALUE.SPOILERS_LEFT_POSITION, new ValueEntry("Position", 2) },
            { TOGGLE_VALUE.SPOILERS_RIGHT_POSITION, new ValueEntry("Position", 2) },
            { TOGGLE_VALUE.FLAPS_HANDLE_PERCENT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.TRAILING_EDGE_FLAPS_LEFT_PERCENT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.TRAILING_EDGE_FLAPS_RIGHT_PERCENT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.LEADING_EDGE_FLAPS_LEFT_PERCENT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.LEADING_EDGE_FLAPS_RIGHT_PERCENT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.AILERON_LEFT_DEFLECTION_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.AILERON_RIGHT_DEFLECTION_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.AILERON_TRIM, new ValueEntry("Radians", 2) },
            { TOGGLE_VALUE.AILERON_TRIM_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.RUDDER_DEFLECTION_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.RUDDER_TRIM_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.ELEVATOR_DEFLECTION_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.AUTOPILOT_HEADING_LOCK_DIR, new ValueEntry("Degrees", 0) },
            { TOGGLE_VALUE.AUTOPILOT_HEADING_LOCK_DIR__1, new ValueEntry("Degrees", 0) },
            { TOGGLE_VALUE.AUTOPILOT_ALTITUDE_LOCK_VAR, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.AUTOPILOT_ALTITUDE_LOCK_VAR__1, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.AUTOPILOT_ALTITUDE_LOCK_VAR__2, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.AUTOPILOT_ALTITUDE_LOCK_VAR__3, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.AUTOPILOT_VERTICAL_HOLD_VAR, new ValueEntry("Feet/minute", 0) },
            { TOGGLE_VALUE.AUTOPILOT_VERTICAL_HOLD_VAR__1, new ValueEntry("Feet/minute", 0) },
            { TOGGLE_VALUE.AUTOPILOT_VERTICAL_HOLD_VAR__2, new ValueEntry("Feet/minute", 0) },
            { TOGGLE_VALUE.AUTOPILOT_VERTICAL_HOLD_VAR__3, new ValueEntry("Feet/minute", 0) },
            { TOGGLE_VALUE.AUTOPILOT_AIRSPEED_HOLD_VAR, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.AUTOPILOT_AIRSPEED_HOLD_VAR__1, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.AUTOPILOT_AIRSPEED_HOLD_VAR__2, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.GEAR_HYDRAULIC_PRESSURE, new ValueEntry("Pound force per square foot (psf)", 2) },
            { TOGGLE_VALUE.GEAR_CENTER_POSITION, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GEAR_LEFT_POSITION, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GEAR_RIGHT_POSITION, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GEAR_TAIL_POSITION, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GEAR_AUX_POSITION, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GEAR_TOTAL_PCT_EXTENDED, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.WATER_RUDDER_HANDLE_POSITION, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.WATER_LEFT_RUDDER_EXTENDED, new ValueEntry("Percentage", 0) },
            { TOGGLE_VALUE.WATER_RIGHT_RUDDER_EXTENDED, new ValueEntry("Percentage", 0) },
            { TOGGLE_VALUE.GEAR_CENTER_STEER_ANGLE, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GEAR_LEFT_STEER_ANGLE, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GEAR_RIGHT_STEER_ANGLE, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GEAR_AUX_STEER_ANGLE, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.WATER_LEFT_RUDDER_STEER_ANGLE, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.WATER_RIGHT_RUDDER_STEER_ANGLE, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GEAR_CENTER_STEER_ANGLE_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GEAR_LEFT_STEER_ANGLE_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GEAR_RIGHT_STEER_ANGLE_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GEAR_AUX_STEER_ANGLE_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.WATER_LEFT_RUDDER_STEER_ANGLE_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.WATER_RIGHT_RUDDER_STEER_ANGLE_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.CENTER_WHEEL_RPM, new ValueEntry("Rpm", 0) },
            { TOGGLE_VALUE.LEFT_WHEEL_RPM, new ValueEntry("Rpm", 0) },
            { TOGGLE_VALUE.RIGHT_WHEEL_RPM, new ValueEntry("Rpm", 0) },
            { TOGGLE_VALUE.AUX_WHEEL_RPM, new ValueEntry("Rpm", 0) },
            { TOGGLE_VALUE.RETRACT_LEFT_FLOAT_EXTENDED, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.RETRACT_RIGHT_FLOAT_EXTENDED, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.STEER_INPUT_CONTROL, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.AMBIENT_DENSITY, new ValueEntry("Slugs per cubic feet", 0) },
            { TOGGLE_VALUE.AMBIENT_TEMPERATURE, new ValueEntry("Celsius", 2) },
            { TOGGLE_VALUE.AMBIENT_PRESSURE, new ValueEntry("inHg", 2) },
            { TOGGLE_VALUE.AMBIENT_WIND_VELOCITY, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.AMBIENT_WIND_DIRECTION, new ValueEntry("Degrees", 0) },
            { TOGGLE_VALUE.AMBIENT_WIND_X, new ValueEntry("Meters per second", 0) },
            { TOGGLE_VALUE.AMBIENT_WIND_Y, new ValueEntry("Meters per second", 0) },
            { TOGGLE_VALUE.AMBIENT_WIND_Z, new ValueEntry("Meters per second", 0) },
            { TOGGLE_VALUE.STRUCT_AMBIENT_WIND, new ValueEntry("Feet_per_second", 0) },
            { TOGGLE_VALUE.AIRCRAFT_WIND_X, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.AIRCRAFT_WIND_Y, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.AIRCRAFT_WIND_Z, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.BAROMETER_PRESSURE, new ValueEntry("Millibars", 0) },
            { TOGGLE_VALUE.SEA_LEVEL_PRESSURE, new ValueEntry("Millibars", 0) },
            { TOGGLE_VALUE.TOTAL_AIR_TEMPERATURE, new ValueEntry("Celsius", 2) },
            { TOGGLE_VALUE.AMBIENT_VISIBILITY, new ValueEntry("Meters", 0) },
            { TOGGLE_VALUE.STANDARD_ATM_TEMPERATURE, new ValueEntry("Celsius", 0) },
            { TOGGLE_VALUE.FOLDING_WING_LEFT_PERCENT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.FOLDING_WING_RIGHT_PERCENT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.CANOPY_OPEN, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.TAILHOOK_POSITION, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.ELECTRICAL_TOTAL_LOAD_AMPS, new ValueEntry("Amperes", 2) },
            { TOGGLE_VALUE.ELECTRICAL_BATTERY_LOAD, new ValueEntry("Amperes", 2) },
            { TOGGLE_VALUE.ELECTRICAL_BATTERY_VOLTAGE, new ValueEntry("Volts", 2) },
            { TOGGLE_VALUE.ELECTRICAL_MAIN_BUS_VOLTAGE, new ValueEntry("Volts", 2) },
            { TOGGLE_VALUE.ELECTRICAL_MAIN_BUS_AMPS, new ValueEntry("Amperes", 2) },
            { TOGGLE_VALUE.ELECTRICAL_AVIONICS_BUS_VOLTAGE, new ValueEntry("Volts", 2) },
            { TOGGLE_VALUE.ELECTRICAL_AVIONICS_BUS_AMPS, new ValueEntry("Amperes", 2) },
            { TOGGLE_VALUE.ELECTRICAL_HOT_BATTERY_BUS_VOLTAGE, new ValueEntry("Volts", 2) },
            { TOGGLE_VALUE.ELECTRICAL_HOT_BATTERY_BUS_AMPS, new ValueEntry("Amperes", 2) },
            { TOGGLE_VALUE.ELECTRICAL_BATTERY_BUS_VOLTAGE, new ValueEntry("Volts", 2) },
            { TOGGLE_VALUE.ELECTRICAL_BATTERY_BUS_AMPS, new ValueEntry("Amperes", 2) },
            { TOGGLE_VALUE.ELECTRICAL_BATTERY_BUS_CONTACT_SWITCH, new ValueEntry("Volts", 2) },
            { TOGGLE_VALUE.HYDRAULIC_SYSTEM_INTEGRITY, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.TOTAL_WEIGHT, new ValueEntry("Pounds", 0) },
            { TOGGLE_VALUE.MAX_GROSS_WEIGHT, new ValueEntry("Pounds", 0) },
            { TOGGLE_VALUE.EMPTY_WEIGHT, new ValueEntry("Pounds", 0) },
            { TOGGLE_VALUE.G_FORCE, new ValueEntry("GForce", 2) },
            { TOGGLE_VALUE.DESIGN_SPEED_VS0, new ValueEntry("Feet per second", 0) },
            { TOGGLE_VALUE.DESIGN_SPEED_VS1, new ValueEntry("Feet per second", 0) },
            { TOGGLE_VALUE.DESIGN_SPEED_VC, new ValueEntry("Feet per second", 0) },
            { TOGGLE_VALUE.MIN_DRAG_VELOCITY, new ValueEntry("Feet per second", 0) },
            { TOGGLE_VALUE.ESTIMATED_CRUISE_SPEED, new ValueEntry("Feet per second", 0) },
            { TOGGLE_VALUE.CG_PERCENT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.CG_PERCENT_LATERAL, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.ATC_SUGGESTED_MIN_RWY_TAKEOFF, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.ATC_SUGGESTED_MIN_RWY_LANDING, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.TYPICAL_DESCENT_RATE, new ValueEntry("Feet per minute", 0) },
            { TOGGLE_VALUE.VISUAL_MODEL_RADIUS, new ValueEntry("Meters", 2) },
            { TOGGLE_VALUE.DYNAMIC_PRESSURE, new ValueEntry("Pounds per square foot", 0) },
            { TOGGLE_VALUE.TOTAL_VELOCITY, new ValueEntry("Feet per second", 0) },
            { TOGGLE_VALUE.AIRSPEED_SELECT_INDICATED_OR_TRUE, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.VARIOMETER_RATE, new ValueEntry("Feet per second", 0) },
            { TOGGLE_VALUE.PRESSURE_ALTITUDE, new ValueEntry("Meters", 0) },
            { TOGGLE_VALUE.MAGNETIC_COMPASS, new ValueEntry("Degrees", 0) },
            { TOGGLE_VALUE.BRAKE_DEPENDENT_HYDRAULIC_PRESSURE, new ValueEntry("Pounds per square foot", 2) },
            { TOGGLE_VALUE.WING_AREA, new ValueEntry("Square feet", 2) },
            { TOGGLE_VALUE.WING_SPAN, new ValueEntry("Feet", 2) },
            { TOGGLE_VALUE.LINEAR_CL_ALPHA, new ValueEntry("Per radian", 2) },
            { TOGGLE_VALUE.CG_AFT_LIMIT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.CG_FWD_LIMIT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.CG_MAX_MACH, new ValueEntry("Machs", 2) },
            { TOGGLE_VALUE.CG_MIN_MACH, new ValueEntry("Machs", 2) },
            { TOGGLE_VALUE.EXIT_POSX, new ValueEntry("Feet", 2) },
            { TOGGLE_VALUE.EXIT_POSY, new ValueEntry("Feet", 2) },
            { TOGGLE_VALUE.EXIT_POSZ, new ValueEntry("Feet", 2) },
            { TOGGLE_VALUE.DECISION_HEIGHT, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.DECISION_ALTITUDE_MSL, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.EMPTY_WEIGHT_PITCH_MOI, new ValueEntry("Slugs per feet squared", 2) },
            { TOGGLE_VALUE.EMPTY_WEIGHT_ROLL_MOI, new ValueEntry("Slugs per feet squared", 2) },
            { TOGGLE_VALUE.EMPTY_WEIGHT_YAW_MOI, new ValueEntry("Slugs per feet squared", 2) },
            { TOGGLE_VALUE.EMPTY_WEIGHT_CROSS_COUPLED_MOI, new ValueEntry("Slugs per feet squared", 2) },
            { TOGGLE_VALUE.TOTAL_WEIGHT_PITCH_MOI, new ValueEntry("Slugs per feet squared", 2) },
            { TOGGLE_VALUE.TOTAL_WEIGHT_ROLL_MOI, new ValueEntry("Slugs per feet squared", 2) },
            { TOGGLE_VALUE.TOTAL_WEIGHT_YAW_MOI, new ValueEntry("Slugs per feet squared", 2) },
            { TOGGLE_VALUE.TOTAL_WEIGHT_CROSS_COUPLED_MOI, new ValueEntry("Slugs per feet squared", 2) },
            { TOGGLE_VALUE.MAX_RATED_ENGINE_RPM, new ValueEntry("Rpm", 0) },
            { TOGGLE_VALUE.MANUAL_FUEL_PUMP_HANDLE, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.ELECTRICAL_OLD_CHARGING_AMPS, new ValueEntry("Amps", 2) },
            { TOGGLE_VALUE.CONCORDE_VISOR_POSITION_PERCENT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.PITOT_ICE_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.SIMULATED_RADIUS, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.STRUCTURAL_ICE_PCT, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.ARTIFICIAL_GROUND_ELEVATION, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.PUSHBACK_CONTACTX, new ValueEntry("Feet", 2) },
            { TOGGLE_VALUE.PUSHBACK_CONTACTY, new ValueEntry("Feet", 2) },
            { TOGGLE_VALUE.PUSHBACK_CONTACTZ, new ValueEntry("Feet", 2) },
            { TOGGLE_VALUE.YAW_STRING_PCT_EXTENDED, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.INDUCTOR_COMPASS_PERCENT_DEVIATION, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.ANEMOMETER_PCT_RPM, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.NAV_VOR_LLAF64, new ValueEntry("LLA structure", 0) },
            { TOGGLE_VALUE.NAV_GS_LLAF64, new ValueEntry("LLA structure", 0) },
            { TOGGLE_VALUE.STATIC_CG_TO_GROUND, new ValueEntry("Feet", 2) },
            { TOGGLE_VALUE.TOW_RELEASE_HANDLE, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.APU_PCT_RPM, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.APU_PCT_STARTER, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.APU_VOLTS, new ValueEntry("Volts", 2) },
            { TOGGLE_VALUE.PRESSURIZATION_CABIN_ALTITUDE, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.PRESSURIZATION_CABIN_ALTITUDE_GOAL, new ValueEntry("Feet", 0) },
            { TOGGLE_VALUE.PRESSURIZATION_CABIN_ALTITUDE_RATE, new ValueEntry("Feet per second", 0) },
            { TOGGLE_VALUE.PRESSURIZATION_PRESSURE_DIFFERENTIAL, new ValueEntry("Pounds per square foot", 0) },
            { TOGGLE_VALUE.NAV_ACTIVE_FREQUENCY__1, new ValueEntry("MHz", 2) },
            { TOGGLE_VALUE.NAV_STANDBY_FREQUENCY__1, new ValueEntry("MHz", 2) },
            { TOGGLE_VALUE.NAV_ACTIVE_FREQUENCY__2, new ValueEntry("MHz", 2) },
            { TOGGLE_VALUE.NAV_STANDBY_FREQUENCY__2, new ValueEntry("MHz", 2) },
            { TOGGLE_VALUE.COM_ACTIVE_FREQUENCY__1, new ValueEntry("MHz", 3) },
            { TOGGLE_VALUE.COM_STANDBY_FREQUENCY__1, new ValueEntry("MHz", 3) },
            { TOGGLE_VALUE.COM_ACTIVE_FREQUENCY__2, new ValueEntry("MHz", 3) },
            { TOGGLE_VALUE.COM_STANDBY_FREQUENCY__2, new ValueEntry("MHz", 3) },
            { TOGGLE_VALUE.PLANE_PITCH_DEGREES, new ValueEntry("Degrees", 2) },
            { TOGGLE_VALUE.PLANE_BANK_DEGREES, new ValueEntry("Degrees", 2) },
            { TOGGLE_VALUE.PLANE_HEADING_DEGREES_TRUE, new ValueEntry("Degrees", 2) },
            { TOGGLE_VALUE.PLANE_HEADING_DEGREES_MAGNETIC, new ValueEntry("Degrees", 2) },
            { TOGGLE_VALUE.TURB_ENG_MAX_TORQUE_PERCENT__1, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.TURB_ENG_MAX_TORQUE_PERCENT__2, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GENERAL_ENG_PCT_MAX_RPM__1, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.GENERAL_ENG_PCT_MAX_RPM__2, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.TURB_ENG_PRIMARY_NOZZLE_PERCENT__1, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.TURB_ENG_PRIMARY_NOZZLE_PERCENT__2, new ValueEntry("Percent", 0) },
            { TOGGLE_VALUE.NAV_OBS__1, new ValueEntry("Degrees", 0) },
            { TOGGLE_VALUE.NAV_OBS__2, new ValueEntry("Degrees", 0) },
            { TOGGLE_VALUE.NAV_DME__1, new ValueEntry("Nautical miles", 1) },
            { TOGGLE_VALUE.NAV_DME__2, new ValueEntry("Nautical miles", 1) },
            { TOGGLE_VALUE.NAV_DMESPEED__1, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.NAV_DMESPEED__2, new ValueEntry("Knots", 0) },
            { TOGGLE_VALUE.RECIP_ENG_COWL_FLAP_POSITION__1, new ValueEntry("Percent", 2) },
            { TOGGLE_VALUE.TURN_COORDINATOR_BALL, new ValueEntry("Position 128", 0) },
            { TOGGLE_VALUE.RECIP_ENG_MANIFOLD_PRESSURE__1, new ValueEntry("Psi", 0) },
            { TOGGLE_VALUE.RECIP_ENG_MANIFOLD_PRESSURE__2, new ValueEntry("Psi", 0) },
            { TOGGLE_VALUE.RECIP_ENG_MANIFOLD_PRESSURE__3, new ValueEntry("Psi", 0) },
            { TOGGLE_VALUE.RECIP_ENG_MANIFOLD_PRESSURE__4, new ValueEntry("Psi", 0) },
            { TOGGLE_VALUE.TURB_ENG_JET_THRUST__1, new ValueEntry("Pounds", 2) },
            { TOGGLE_VALUE.TURB_ENG_JET_THRUST__2, new ValueEntry("Pounds", 2) },
            { TOGGLE_VALUE.TURB_ENG_JET_THRUST__3, new ValueEntry("Pounds", 2) },
            { TOGGLE_VALUE.TURB_ENG_JET_THRUST__4, new ValueEntry("Pounds", 2) },
            { TOGGLE_VALUE.PROP_THRUST__1, new ValueEntry("Pounds", 2) },
            { TOGGLE_VALUE.PROP_THRUST__2, new ValueEntry("Pounds", 2) },
            { TOGGLE_VALUE.PROP_THRUST__3, new ValueEntry("Pounds", 2) },
            { TOGGLE_VALUE.PROP_THRUST__4, new ValueEntry("Pounds", 2) },
            { TOGGLE_VALUE.PROP_RPM__1, new ValueEntry("Rpm", 1) },
            { TOGGLE_VALUE.PROP_RPM__2, new ValueEntry("Rpm", 1) },
            { TOGGLE_VALUE.PROP_RPM__3, new ValueEntry("Rpm", 1) },
            { TOGGLE_VALUE.PROP_RPM__4, new ValueEntry("Rpm", 1) },
        };

        public static string GetUnit(this TOGGLE_VALUE value, string unit)
        {
            if (!string.IsNullOrEmpty(unit))
            {
                // TODO: add some validation
                return unit;
            }
            else if (availableValues.ContainsKey(value))
            {
                return availableValues[value].Unit;
            }
            return DEFAULT_UNIT;
        }

        public static int GetDecimals(this TOGGLE_VALUE value, int? decimals = null)
        {
            if (decimals.HasValue)
            {
                return decimals.Value;
            }
            else if (availableValues.ContainsKey(value))
            {
                return availableValues[value].Decimals;
            }

            return DEFAULT_DECIMALS;
        }
    }
}
