using System.Collections.Generic;

namespace FlightStreamDeck.Core;

public static class KnownVariables
{
    record ValueEntry(string Unit, short Decimals);

    const string DEFAULT_UNIT = "number";
    const int DEFAULT_DECIMALS = 0;

    static Dictionary<string, ValueEntry?> availableValues = new()
    {
        { "ACCELERATION BODY X", new ValueEntry("meter per second squared", 2) },
        { "ACCELERATION BODY Y", new ValueEntry("meter per second squared", 2) },
        { "ACCELERATION BODY Z", new ValueEntry("meter per second squared", 2) },
        { "ACCELERATION WORLD X", new ValueEntry("meter per second squared", 2) },
        { "ACCELERATION WORLD Y", new ValueEntry("meter per second squared", 2) },
        { "ACCELERATION WORLD Z", new ValueEntry("meter per second squared", 2) },
        { "GENERAL ENG RPM:1", new ValueEntry("Rpm", 1) },
        { "GENERAL ENG RPM:2", new ValueEntry("Rpm", 1) },
        { "GENERAL ENG RPM:3", new ValueEntry("Rpm", 1) },
        { "GENERAL ENG RPM:4", new ValueEntry("Rpm", 1) },
        { "GENERAL ENG THROTTLE LEVER POSITION:1", new ValueEntry("Percent", 2) },
        { "GENERAL ENG THROTTLE LEVER POSITION:2", new ValueEntry("Percent", 2) },
        { "GENERAL ENG THROTTLE LEVER POSITION:3", new ValueEntry("Percent", 2) },
        { "GENERAL ENG THROTTLE LEVER POSITION:4", new ValueEntry("Percent", 2) },
        { "GENERAL ENG MIXTURE LEVER POSITION:1", new ValueEntry("Percent", 2) },
        { "GENERAL ENG MIXTURE LEVER POSITION:2", new ValueEntry("Percent", 2) },
        { "GENERAL ENG MIXTURE LEVER POSITION:3", new ValueEntry("Percent", 2) },
        { "GENERAL ENG MIXTURE LEVER POSITION:4", new ValueEntry("Percent", 2) },
        { "GENERAL ENG PROPELLER LEVER POSITION:1", new ValueEntry("Percent", 2) },
        { "GENERAL ENG PROPELLER LEVER POSITION:2", new ValueEntry("Percent", 2) },
        { "GENERAL ENG PROPELLER LEVER POSITION:3", new ValueEntry("Percent", 2) },
        { "GENERAL ENG PROPELLER LEVER POSITION:4", new ValueEntry("Percent", 2) },
        { "GENERAL ENG EXHAUST GAS TEMPERATURE:1", new ValueEntry("Celsius", 0) },
        { "GENERAL ENG EXHAUST GAS TEMPERATURE:2", new ValueEntry("Celsius", 0) },
        { "GENERAL ENG EXHAUST GAS TEMPERATURE:3", new ValueEntry("Celsius", 0) },
        { "GENERAL ENG EXHAUST GAS TEMPERATURE:4", new ValueEntry("Celsius", 0) },
        { "GENERAL ENG FUEL PRESSURE:1", new ValueEntry("Psi", 0) },
        { "GENERAL ENG FUEL PRESSURE:2", new ValueEntry("Psi", 0) },
        { "GENERAL ENG FUEL PRESSURE:3", new ValueEntry("Psi", 0) },
        { "GENERAL ENG FUEL PRESSURE:4", new ValueEntry("Psi", 0) },
        { "GENERAL ENG FUEL USED SINCE START", new ValueEntry("Pounds", 2) },
        { "ENG MAX RPM", new ValueEntry("Rpm", 1) },
        { "ENG FUEL FLOW GPH:1", new ValueEntry("Gallons per hour", 0) },
        { "ENG FUEL FLOW GPH:2", new ValueEntry("Gallons per hour", 0) },
        { "ENG FUEL FLOW GPH:3", new ValueEntry("Gallons per hour", 0) },
        { "ENG FUEL FLOW GPH:4", new ValueEntry("Gallons per hour", 0) },
        { "ENG FUEL FLOW PPH:1", new ValueEntry("Pounds per hour", 0) },
        { "ENG FUEL FLOW PPH:2", new ValueEntry("Pounds per hour", 0) },
        { "ENG FUEL FLOW PPH:3", new ValueEntry("Pounds per hour", 0) },
        { "ENG FUEL FLOW PPH:4", new ValueEntry("Pounds per hour", 0) },
        { "TURB ENG CORRECTED N1:1", new ValueEntry("Percent", 0) },
        { "TURB ENG CORRECTED N1:2", new ValueEntry("Percent", 0) },
        { "TURB ENG CORRECTED N1:3", new ValueEntry("Percent", 0) },
        { "TURB ENG CORRECTED N1:4", new ValueEntry("Percent", 0) },
        { "TURB ENG CORRECTED N2:1", new ValueEntry("Percent", 0) },
        { "TURB ENG CORRECTED N2:2", new ValueEntry("Percent", 0) },
        { "TURB ENG CORRECTED N2:3", new ValueEntry("Percent", 0) },
        { "TURB ENG CORRECTED N2:4", new ValueEntry("Percent", 0) },
        { "TURB ENG ITT:1", new ValueEntry("Celsius", 0) },
        { "TURB ENG ITT:2", new ValueEntry("Celsius", 0) },
        { "TURB ENG ITT:3", new ValueEntry("Celsius", 0) },
        { "TURB ENG ITT:4", new ValueEntry("Celsius", 0) },
        { "TURB ENG AFTERBURNER PCT ACTIVE", new ValueEntry("Percent", 0) },
        { "FUEL TANK CENTER LEVEL", new ValueEntry("Percent", 0) },
        { "FUEL TANK CENTER2 LEVEL", new ValueEntry("Percent", 0) },
        { "FUEL TANK CENTER3 LEVEL", new ValueEntry("Percent", 0) },
        { "FUEL TANK LEFT MAIN LEVEL", new ValueEntry("Percent", 0) },
        { "FUEL TANK LEFT AUX LEVEL", new ValueEntry("Percent", 0) },
        { "FUEL TANK LEFT TIP LEVEL", new ValueEntry("Percent", 0) },
        { "FUEL TANK RIGHT MAIN LEVEL", new ValueEntry("Percent", 0) },
        { "FUEL TANK RIGHT AUX LEVEL", new ValueEntry("Percent", 0) },
        { "FUEL TANK RIGHT TIP LEVEL", new ValueEntry("Percent", 0) },
        { "FUEL TANK EXTERNAL1 LEVEL", new ValueEntry("Percent", 0) },
        { "FUEL TANK EXTERNAL2 LEVEL", new ValueEntry("Percent", 0) },
        { "FUEL TANK CENTER CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK CENTER2 CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK CENTER3 CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK LEFT MAIN CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK LEFT AUX CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK LEFT TIP CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK RIGHT MAIN CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK RIGHT AUX CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK RIGHT TIP CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK EXTERNAL1 CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK EXTERNAL2 CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL LEFT CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL RIGHT CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK CENTER QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK CENTER2 QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK CENTER3 QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK LEFT MAIN QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK LEFT AUX QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK LEFT TIP QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK RIGHT MAIN QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK RIGHT AUX QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK RIGHT TIP QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK EXTERNAL1 QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL TANK EXTERNAL2 QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL LEFT QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL RIGHT QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL TOTAL QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL WEIGHT PER GALLON", new ValueEntry("Pounds", 2) },
        { "FUEL TOTAL CAPACITY", new ValueEntry("Gallons", 2) },
        { "FUEL SELECTED QUANTITY PERCENT", new ValueEntry("Percent", 2) },
        { "FUEL SELECTED QUANTITY", new ValueEntry("Gallons", 2) },
        { "FUEL TOTAL QUANTITY WEIGHT", new ValueEntry("Pounds", 2) },
        { "ESTIMATED FUEL FLOW", new ValueEntry("Pounds per hour", 2) },
        { "GROUND VELOCITY", new ValueEntry("Knots", 0) },
        { "TOTAL WORLD VELOCITY", new ValueEntry("meter per second", 2) },
        { "VELOCITY BODY Z", new ValueEntry("meter per second", 0) },
        { "VELOCITY BODY X", new ValueEntry("meter per second", 0) },
        { "VELOCITY BODY Y", new ValueEntry("meter per second", 0) },
        { "VELOCITY WORLD Z", new ValueEntry("meter per second", 0) },
        { "VELOCITY WORLD X", new ValueEntry("meter per second", 0) },
        { "VELOCITY WORLD Y", new ValueEntry("meter per second", 0) },
        { "ROTATION VELOCITY BODY X", new ValueEntry("meter per second", 2) },
        { "ROTATION VELOCITY BODY Y", new ValueEntry("meter per second", 2) },
        { "ROTATION VELOCITY BODY Z", new ValueEntry("meter per second", 2) },
        { "RELATIVE WIND VELOCITY BODY X", new ValueEntry("meter per second", 2) },
        { "RELATIVE WIND VELOCITY BODY Y", new ValueEntry("meter per second", 2) },
        { "RELATIVE WIND VELOCITY BODY Z", new ValueEntry("meter per second", 2) },
        { "PLANE ALT ABOVE GROUND", new ValueEntry("Feet", 2) },
        { "PLANE ALTITUDE", new ValueEntry("Feet", 2) },
        { "MAGVAR", new ValueEntry("Degrees", 0) },
        { "GROUND ALTITUDE", new ValueEntry("Meters", 2) },
        { "AIRSPEED TRUE", new ValueEntry("Knots", 0) },
        { "AIRSPEED INDICATED", new ValueEntry("Knots", 0) },
        { "AIRSPEED TRUE CALIBRATE", new ValueEntry("Degrees", 0) },
        { "AIRSPEED BARBER POLE", new ValueEntry("Knots", 0) },
        { "AIRSPEED MACH", new ValueEntry("Mach", 2) },
        { "VERTICAL SPEED", new ValueEntry("Feet per minute", 0) },
        { "MACH MAX OPERATE", new ValueEntry("Mach", 2) },
        { "BARBER POLE MACH", new ValueEntry("Mach", 2) },
        { "INDICATED ALTITUDE", new ValueEntry("Feet", 0) },
        { "KOHLSMAN SETTING MB", new ValueEntry("Millibars", 0) },
        { "KOHLSMAN SETTING HG", new ValueEntry("inHg", 2) },
        { "ATTITUDE BARS POSITION", new ValueEntry("Percent", 0) },
        { "WISKEY COMPASS INDICATION DEGREES", new ValueEntry("Degrees", 0) },
        { "RADIO HEIGHT", new ValueEntry("Feet", 0) },
        { "MAX G FORCE", new ValueEntry("Gforce", 2) },
        { "MIN G FORCE", new ValueEntry("Gforce", 2) },
        { "SUCTION PRESSURE", new ValueEntry("inHg", 2) },
        { "ADF CARD", new ValueEntry("Degrees", 0) },
        { "HSI BEARING", new ValueEntry("Degrees", 0) },
        { "HSI SPEED", new ValueEntry("Knots", 0) },
        { "HSI DISTANCE", new ValueEntry("Nautical miles", 2) },
        { "GPS POSITION LAT", new ValueEntry("Degrees", 10) },
        { "GPS POSITION LON", new ValueEntry("Degrees", 10) },
        { "GPS POSITION ALT", new ValueEntry("Meters", 2) },
        { "GPS GROUND SPEED", new ValueEntry("Meters per second", 2) },
        { "GPS WP DISTANCE", new ValueEntry("Meters", 2) },
        { "GPS WP CROSS TRK", new ValueEntry("Meters", 2) },
        { "GPS WP VERTICAL SPEED", new ValueEntry("Meters per second", 2) },
        { "GPS ETE", new ValueEntry("Seconds", 0) },
        { "GPS ETA", new ValueEntry("Seconds", 0) },
        { "GPS WP NEXT LAT", new ValueEntry("Degrees", 10) },
        { "GPS WP NEXT LON", new ValueEntry("Degrees", 10) },
        { "GPS WP NEXT ALT", new ValueEntry("Meters", 0) },
        { "GPS WP PREV LAT", new ValueEntry("Degrees", 10) },
        { "GPS WP PREV LON", new ValueEntry("Degrees", 10) },
        { "GPS WP PREV ALT", new ValueEntry("Meters", 0) },
        { "GPS WP ETE", new ValueEntry("Seconds", 0) },
        { "GPS WP ETA", new ValueEntry("Seconds", 0) },
        { "GPS APPROACH TIMEZONE DEVIATION", new ValueEntry("Seconds", 0) },
        { "GPS TARGET DISTANCE", new ValueEntry("Meters", 2) },
        { "GPS TARGET ALTITUDE", new ValueEntry("Meters", 2) },
        { "ELEVATOR TRIM POSITION", new ValueEntry("Radians", 2) },
        { "ELEVATOR TRIM PCT", new ValueEntry("Percent", 0) },
        { "SPOILERS HANDLE POSITION", new ValueEntry("Position", 2) },
        { "SPOILERS LEFT POSITION", new ValueEntry("Position", 2) },
        { "SPOILERS RIGHT POSITION", new ValueEntry("Position", 2) },
        { "FLAPS HANDLE PERCENT", new ValueEntry("Percent", 0) },
        { "TRAILING EDGE FLAPS LEFT PERCENT", new ValueEntry("Percent", 0) },
        { "TRAILING EDGE FLAPS RIGHT PERCENT", new ValueEntry("Percent", 0) },
        { "LEADING EDGE FLAPS LEFT PERCENT", new ValueEntry("Percent", 0) },
        { "LEADING EDGE FLAPS RIGHT PERCENT", new ValueEntry("Percent", 0) },
        { "AILERON LEFT DEFLECTION PCT", new ValueEntry("Percent", 0) },
        { "AILERON RIGHT DEFLECTION PCT", new ValueEntry("Percent", 0) },
        { "AILERON TRIM", new ValueEntry("Radians", 2) },
        { "AILERON TRIM PCT", new ValueEntry("Percent", 0) },
        { "RUDDER DEFLECTION PCT", new ValueEntry("Percent", 0) },
        { "RUDDER TRIM PCT", new ValueEntry("Percent", 0) },
        { "ELEVATOR DEFLECTION PCT", new ValueEntry("Percent", 0) },
        { "AUTOPILOT HEADING LOCK DIR", new ValueEntry("Degrees", 0) },
        { "AUTOPILOT HEADING LOCK DIR:1", new ValueEntry("Degrees", 0) },
        { "AUTOPILOT ALTITUDE LOCK VAR", new ValueEntry("Feet", 0) },
        { "AUTOPILOT ALTITUDE LOCK VAR:1", new ValueEntry("Feet", 0) },
        { "AUTOPILOT ALTITUDE LOCK VAR:2", new ValueEntry("Feet", 0) },
        { "AUTOPILOT ALTITUDE LOCK VAR:3", new ValueEntry("Feet", 0) },
        { "AUTOPILOT VERTICAL HOLD VAR", new ValueEntry("Feet/minute", 0) },
        { "AUTOPILOT VERTICAL HOLD VAR:1", new ValueEntry("Feet/minute", 0) },
        { "AUTOPILOT VERTICAL HOLD VAR:2", new ValueEntry("Feet/minute", 0) },
        { "AUTOPILOT VERTICAL HOLD VAR:3", new ValueEntry("Feet/minute", 0) },
        { "AUTOPILOT AIRSPEED HOLD VAR", new ValueEntry("Knots", 0) },
        { "AUTOPILOT AIRSPEED HOLD VAR:1", new ValueEntry("Knots", 0) },
        { "AUTOPILOT AIRSPEED HOLD VAR:2", new ValueEntry("Knots", 0) },
        { "GEAR HYDRAULIC PRESSURE", new ValueEntry("Pound force per square foot (psf)", 2) },
        { "GEAR CENTER POSITION", new ValueEntry("Percent", 0) },
        { "GEAR LEFT POSITION", new ValueEntry("Percent", 0) },
        { "GEAR RIGHT POSITION", new ValueEntry("Percent", 0) },
        { "GEAR TAIL POSITION", new ValueEntry("Percent", 0) },
        { "GEAR AUX POSITION", new ValueEntry("Percent", 0) },
        { "GEAR TOTAL PCT EXTENDED", new ValueEntry("Percent", 0) },
        { "WATER RUDDER HANDLE POSITION", new ValueEntry("Percent", 0) },
        { "WATER LEFT RUDDER EXTENDED", new ValueEntry("Percentage", 0) },
        { "WATER RIGHT RUDDER EXTENDED", new ValueEntry("Percentage", 0) },
        { "GEAR CENTER STEER ANGLE", new ValueEntry("Percent", 0) },
        { "GEAR LEFT STEER ANGLE", new ValueEntry("Percent", 0) },
        { "GEAR RIGHT STEER ANGLE", new ValueEntry("Percent", 0) },
        { "GEAR AUX STEER ANGLE", new ValueEntry("Percent", 0) },
        { "WATER LEFT RUDDER STEER ANGLE", new ValueEntry("Percent", 0) },
        { "WATER RIGHT RUDDER STEER ANGLE", new ValueEntry("Percent", 0) },
        { "GEAR CENTER STEER ANGLE PCT", new ValueEntry("Percent", 0) },
        { "GEAR LEFT STEER ANGLE PCT", new ValueEntry("Percent", 0) },
        { "GEAR RIGHT STEER ANGLE PCT", new ValueEntry("Percent", 0) },
        { "GEAR AUX STEER ANGLE PCT", new ValueEntry("Percent", 0) },
        { "WATER LEFT RUDDER STEER ANGLE PCT", new ValueEntry("Percent", 0) },
        { "WATER RIGHT RUDDER STEER ANGLE PCT", new ValueEntry("Percent", 0) },
        { "CENTER WHEEL RPM", new ValueEntry("Rpm", 0) },
        { "LEFT WHEEL RPM", new ValueEntry("Rpm", 0) },
        { "RIGHT WHEEL RPM", new ValueEntry("Rpm", 0) },
        { "AUX WHEEL RPM", new ValueEntry("Rpm", 0) },
        { "RETRACT LEFT FLOAT EXTENDED", new ValueEntry("Percent", 0) },
        { "RETRACT RIGHT FLOAT EXTENDED", new ValueEntry("Percent", 0) },
        { "STEER INPUT CONTROL", new ValueEntry("Percent", 0) },
        { "AMBIENT DENSITY", new ValueEntry("Slugs per cubic feet", 0) },
        { "AMBIENT TEMPERATURE", new ValueEntry("Celsius", 2) },
        { "AMBIENT PRESSURE", new ValueEntry("inHg", 2) },
        { "AMBIENT WIND VELOCITY", new ValueEntry("Knots", 0) },
        { "AMBIENT WIND DIRECTION", new ValueEntry("Degrees", 0) },
        { "AMBIENT WIND X", new ValueEntry("Meters per second", 0) },
        { "AMBIENT WIND Y", new ValueEntry("Meters per second", 0) },
        { "AMBIENT WIND Z", new ValueEntry("Meters per second", 0) },
        { "STRUCT AMBIENT WIND", new ValueEntry("Feet per second", 0) },
        { "AIRCRAFT WIND X", new ValueEntry("Knots", 0) },
        { "AIRCRAFT WIND Y", new ValueEntry("Knots", 0) },
        { "AIRCRAFT WIND Z", new ValueEntry("Knots", 0) },
        { "BAROMETER PRESSURE", new ValueEntry("Millibars", 0) },
        { "SEA LEVEL PRESSURE", new ValueEntry("Millibars", 0) },
        { "TOTAL AIR TEMPERATURE", new ValueEntry("Celsius", 2) },
        { "AMBIENT VISIBILITY", new ValueEntry("Meters", 0) },
        { "STANDARD ATM TEMPERATURE", new ValueEntry("Celsius", 0) },
        { "FOLDING WING LEFT PERCENT", new ValueEntry("Percent", 0) },
        { "FOLDING WING RIGHT PERCENT", new ValueEntry("Percent", 0) },
        { "CANOPY OPEN", new ValueEntry("Percent", 0) },
        { "TAILHOOK POSITION", new ValueEntry("Percent", 0) },
        { "ELECTRICAL TOTAL LOAD AMPS", new ValueEntry("Amperes", 2) },
        { "ELECTRICAL BATTERY LOAD", new ValueEntry("Amperes", 2) },
        { "ELECTRICAL BATTERY VOLTAGE", new ValueEntry("Volts", 2) },
        { "ELECTRICAL MAIN BUS VOLTAGE", new ValueEntry("Volts", 2) },
        { "ELECTRICAL MAIN BUS AMPS", new ValueEntry("Amperes", 2) },
        { "ELECTRICAL AVIONICS BUS VOLTAGE", new ValueEntry("Volts", 2) },
        { "ELECTRICAL AVIONICS BUS AMPS", new ValueEntry("Amperes", 2) },
        { "ELECTRICAL HOT BATTERY BUS VOLTAGE", new ValueEntry("Volts", 2) },
        { "ELECTRICAL HOT BATTERY BUS AMPS", new ValueEntry("Amperes", 2) },
        { "ELECTRICAL BATTERY BUS VOLTAGE", new ValueEntry("Volts", 2) },
        { "ELECTRICAL BATTERY BUS AMPS", new ValueEntry("Amperes", 2) },
        { "ELECTRICAL BATTERY BUS CONTACT SWITCH", new ValueEntry("Volts", 2) },
        { "HYDRAULIC SYSTEM INTEGRITY", new ValueEntry("Percent", 0) },
        { "TOTAL WEIGHT", new ValueEntry("Pounds", 0) },
        { "MAX GROSS WEIGHT", new ValueEntry("Pounds", 0) },
        { "EMPTY WEIGHT", new ValueEntry("Pounds", 0) },
        { "G FORCE", new ValueEntry("GForce", 2) },
        { "DESIGN SPEED VS0", new ValueEntry("Feet per second", 0) },
        { "DESIGN SPEED VS1", new ValueEntry("Feet per second", 0) },
        { "DESIGN SPEED VC", new ValueEntry("Feet per second", 0) },
        { "MIN DRAG VELOCITY", new ValueEntry("Feet per second", 0) },
        { "ESTIMATED CRUISE SPEED", new ValueEntry("Feet per second", 0) },
        { "CG PERCENT", new ValueEntry("Percent", 0) },
        { "CG PERCENT LATERAL", new ValueEntry("Percent", 0) },
        { "ATC SUGGESTED MIN RWY TAKEOFF", new ValueEntry("Feet", 0) },
        { "ATC SUGGESTED MIN RWY LANDING", new ValueEntry("Feet", 0) },
        { "TYPICAL DESCENT RATE", new ValueEntry("Feet per minute", 0) },
        { "VISUAL MODEL RADIUS", new ValueEntry("Meters", 2) },
        { "DYNAMIC PRESSURE", new ValueEntry("Pounds per square foot", 0) },
        { "TOTAL VELOCITY", new ValueEntry("Feet per second", 0) },
        { "AIRSPEED SELECT INDICATED OR TRUE", new ValueEntry("Knots", 0) },
        { "VARIOMETER RATE", new ValueEntry("Feet per second", 0) },
        { "PRESSURE ALTITUDE", new ValueEntry("Meters", 0) },
        { "MAGNETIC COMPASS", new ValueEntry("Degrees", 0) },
        { "BRAKE DEPENDENT HYDRAULIC PRESSURE", new ValueEntry("Pounds per square foot", 2) },
        { "WING AREA", new ValueEntry("Square feet", 2) },
        { "WING SPAN", new ValueEntry("Feet", 2) },
        { "LINEAR CL ALPHA", new ValueEntry("Per radian", 2) },
        { "CG AFT LIMIT", new ValueEntry("Percent", 0) },
        { "CG FWD LIMIT", new ValueEntry("Percent", 0) },
        { "CG MAX MACH", new ValueEntry("Machs", 2) },
        { "CG MIN MACH", new ValueEntry("Machs", 2) },
        { "EXIT POSX", new ValueEntry("Feet", 2) },
        { "EXIT POSY", new ValueEntry("Feet", 2) },
        { "EXIT POSZ", new ValueEntry("Feet", 2) },
        { "DECISION HEIGHT", new ValueEntry("Feet", 0) },
        { "DECISION ALTITUDE MSL", new ValueEntry("Feet", 0) },
        { "EMPTY WEIGHT PITCH MOI", new ValueEntry("Slugs per feet squared", 2) },
        { "EMPTY WEIGHT ROLL MOI", new ValueEntry("Slugs per feet squared", 2) },
        { "EMPTY WEIGHT YAW MOI", new ValueEntry("Slugs per feet squared", 2) },
        { "EMPTY WEIGHT CROSS COUPLED MOI", new ValueEntry("Slugs per feet squared", 2) },
        { "TOTAL WEIGHT PITCH MOI", new ValueEntry("Slugs per feet squared", 2) },
        { "TOTAL WEIGHT ROLL MOI", new ValueEntry("Slugs per feet squared", 2) },
        { "TOTAL WEIGHT YAW MOI", new ValueEntry("Slugs per feet squared", 2) },
        { "TOTAL WEIGHT CROSS COUPLED MOI", new ValueEntry("Slugs per feet squared", 2) },
        { "MAX RATED ENGINE RPM", new ValueEntry("Rpm", 0) },
        { "MANUAL FUEL PUMP HANDLE", new ValueEntry("Percent", 0) },
        { "ELECTRICAL OLD CHARGING AMPS", new ValueEntry("Amps", 2) },
        { "CONCORDE VISOR POSITION PERCENT", new ValueEntry("Percent", 0) },
        { "PITOT ICE PCT", new ValueEntry("Percent", 0) },
        { "SIMULATED RADIUS", new ValueEntry("Feet", 0) },
        { "STRUCTURAL ICE PCT", new ValueEntry("Percent", 0) },
        { "ARTIFICIAL GROUND ELEVATION", new ValueEntry("Feet", 0) },
        { "PUSHBACK CONTACTX", new ValueEntry("Feet", 2) },
        { "PUSHBACK CONTACTY", new ValueEntry("Feet", 2) },
        { "PUSHBACK CONTACTZ", new ValueEntry("Feet", 2) },
        { "YAW STRING PCT EXTENDED", new ValueEntry("Percent", 0) },
        { "INDUCTOR COMPASS PERCENT DEVIATION", new ValueEntry("Percent", 0) },
        { "ANEMOMETER PCT RPM", new ValueEntry("Percent", 0) },
        { "NAV VOR LLAF64", new ValueEntry("LLA structure", 0) },
        { "NAV GS LLAF64", new ValueEntry("LLA structure", 0) },
        { "STATIC CG TO GROUND", new ValueEntry("Feet", 2) },
        { "TOW RELEASE HANDLE", new ValueEntry("Percent", 0) },
        { "APU PCT RPM", new ValueEntry("Percent", 0) },
        { "APU PCT STARTER", new ValueEntry("Percent", 0) },
        { "APU VOLTS", new ValueEntry("Volts", 2) },
        { "PRESSURIZATION CABIN ALTITUDE", new ValueEntry("Feet", 0) },
        { "PRESSURIZATION CABIN ALTITUDE GOAL", new ValueEntry("Feet", 0) },
        { "PRESSURIZATION CABIN ALTITUDE RATE", new ValueEntry("Feet per second", 0) },
        { "PRESSURIZATION PRESSURE DIFFERENTIAL", new ValueEntry("Pounds per square foot", 0) },
        { "NAV ACTIVE FREQUENCY:1", new ValueEntry("MHz", 2) },
        { "NAV STANDBY FREQUENCY:1", new ValueEntry("MHz", 2) },
        { "NAV ACTIVE FREQUENCY:2", new ValueEntry("MHz", 2) },
        { "NAV STANDBY FREQUENCY:2", new ValueEntry("MHz", 2) },
        { "COM ACTIVE FREQUENCY:1", new ValueEntry("MHz", 3) },
        { "COM STANDBY FREQUENCY:1", new ValueEntry("MHz", 3) },
        { "COM ACTIVE FREQUENCY:2", new ValueEntry("MHz", 3) },
        { "COM STANDBY FREQUENCY:2", new ValueEntry("MHz", 3) },
        { "ADF ACTIVE FREQUENCY:1", new ValueEntry("MHz", 0) },
        { "ADF STANDBY FREQUENCY:1", new ValueEntry("MHz", 0) },
        { "ADF ACTIVE FREQUENCY:2", new ValueEntry("MHz", 0) },
        { "ADF STANDBY FREQUENCY:2", new ValueEntry("MHz", 0) },
        { "PLANE PITCH DEGREES", new ValueEntry("Degrees", 2) },
        { "PLANE BANK DEGREES", new ValueEntry("Degrees", 2) },
        { "PLANE HEADING DEGREES TRUE", new ValueEntry("Degrees", 2) },
        { "PLANE HEADING DEGREES MAGNETIC", new ValueEntry("Degrees", 2) },
        { "TURB ENG MAX TORQUE PERCENT:1", new ValueEntry("Percent", 0) },
        { "TURB ENG MAX TORQUE PERCENT:2", new ValueEntry("Percent", 0) },
        { "TURB ENG MAX TORQUE PERCENT:3", new ValueEntry("Percent", 0) },
        { "TURB ENG MAX TORQUE PERCENT:4", new ValueEntry("Percent", 0) },
        { "GENERAL ENG PCT MAX RPM:1", new ValueEntry("Percent", 0) },
        { "GENERAL ENG PCT MAX RPM:2", new ValueEntry("Percent", 0) },
        { "GENERAL ENG PCT MAX RPM:3", new ValueEntry("Percent", 0) },
        { "GENERAL ENG PCT MAX RPM:4", new ValueEntry("Percent", 0) },
        { "TURB ENG PRIMARY NOZZLE PERCENT:1", new ValueEntry("Percent", 0) },
        { "TURB ENG PRIMARY NOZZLE PERCENT:2", new ValueEntry("Percent", 0) },
        { "TURB ENG PRIMARY NOZZLE PERCENT:3", new ValueEntry("Percent", 0) },
        { "TURB ENG PRIMARY NOZZLE PERCENT:4", new ValueEntry("Percent", 0) },
        { "NAV OBS:1", new ValueEntry("Degrees", 0) },
        { "NAV OBS:2", new ValueEntry("Degrees", 0) },
        { "NAV DME:1", new ValueEntry("Nautical miles", 1) },
        { "NAV DME:2", new ValueEntry("Nautical miles", 1) },
        { "NAV DMESPEED:1", new ValueEntry("Knots", 0) },
        { "NAV DMESPEED:2", new ValueEntry("Knots", 0) },
        { "RECIP ENG COWL FLAP POSITION:1", new ValueEntry("Percent", 2) },
        { "RECIP ENG COWL FLAP POSITION:2", new ValueEntry("Percent", 2) },
        { "TURN COORDINATOR BALL", new ValueEntry("Position 128", 0) },
        { "RECIP ENG MANIFOLD PRESSURE:1", new ValueEntry("Psi", 0) },
        { "RECIP ENG MANIFOLD PRESSURE:2", new ValueEntry("Psi", 0) },
        { "RECIP ENG MANIFOLD PRESSURE:3", new ValueEntry("Psi", 0) },
        { "RECIP ENG MANIFOLD PRESSURE:4", new ValueEntry("Psi", 0) },
        { "TURB ENG JET THRUST:1", new ValueEntry("Pounds", 2) },
        { "TURB ENG JET THRUST:2", new ValueEntry("Pounds", 2) },
        { "TURB ENG JET THRUST:3", new ValueEntry("Pounds", 2) },
        { "TURB ENG JET THRUST:4", new ValueEntry("Pounds", 2) },
        { "PROP THRUST:1", new ValueEntry("Pounds", 2) },
        { "PROP THRUST:2", new ValueEntry("Pounds", 2) },
        { "PROP THRUST:3", new ValueEntry("Pounds", 2) },
        { "PROP THRUST:4", new ValueEntry("Pounds", 2) },
        { "PROP RPM:1", new ValueEntry("Rpm", 1) },
        { "PROP RPM:2", new ValueEntry("Rpm", 1) },
        { "PROP RPM:3", new ValueEntry("Rpm", 1) },
        { "PROP RPM:4", new ValueEntry("Rpm", 1) },
        { "ENG CYLINDER HEAD TEMPERATURE:1", new ValueEntry("Celsius", 0) },
        { "ENG CYLINDER HEAD TEMPERATURE:2", new ValueEntry("Celsius", 0) },
        { "ENG CYLINDER HEAD TEMPERATURE:3", new ValueEntry("Celsius", 0) },
        { "ENG CYLINDER HEAD TEMPERATURE:4", new ValueEntry("Celsius", 0) },
        { "RECIP ENG CYLINDER HEAD TEMPERATURE:1", new ValueEntry("Celsius", 0) },
        { "RECIP ENG CYLINDER HEAD TEMPERATURE:2", new ValueEntry("Celsius", 0) },
        { "RECIP ENG CYLINDER HEAD TEMPERATURE:3", new ValueEntry("Celsius", 0) },
        { "RECIP ENG CYLINDER HEAD TEMPERATURE:4", new ValueEntry("Celsius", 0) },
        { "ENG OIL TEMPERATURE:1", new ValueEntry("Celsius", 0) },
        { "ENG OIL TEMPERATURE:2", new ValueEntry("Celsius", 0) },
        { "ENG OIL TEMPERATURE:3", new ValueEntry("Celsius", 0) },
        { "ENG OIL TEMPERATURE:4", new ValueEntry("Celsius", 0) },
        { "GENERAL ENG OIL TEMPERATURE:1", new ValueEntry("Celsius", 0) },
        { "GENERAL ENG OIL TEMPERATURE:2", new ValueEntry("Celsius", 0) },
        { "GENERAL ENG OIL TEMPERATURE:3", new ValueEntry("Celsius", 0) },
        { "GENERAL ENG OIL TEMPERATURE:4", new ValueEntry("Celsius", 0) },
        { "ENG OIL PRESSURE:1", new ValueEntry("Psi", 0) },
        { "ENG OIL PRESSURE:2", new ValueEntry("Psi", 0) },
        { "ENG OIL PRESSURE:3", new ValueEntry("Psi", 0) },
        { "ENG OIL PRESSURE:4", new ValueEntry("Psi", 0) },
        { "GENERAL ENG OIL PRESSURE:1", new ValueEntry("Psi", 0) },
        { "GENERAL ENG OIL PRESSURE:2", new ValueEntry("Psi", 0) },
        { "GENERAL ENG OIL PRESSURE:3", new ValueEntry("Psi", 0) },
        { "GENERAL ENG OIL PRESSURE:4", new ValueEntry("Psi", 0) },
        { "RECIP CARBURETOR TEMPERATURE:1", new ValueEntry("Celsius", 0) },
        { "RECIP CARBURETOR TEMPERATURE:2", new ValueEntry("Celsius", 0) },
        { "RECIP CARBURETOR TEMPERATURE:3", new ValueEntry("Celsius", 0) },
        { "RECIP CARBURETOR TEMPERATURE:4", new ValueEntry("Celsius", 0) },
        { "GYRO DRIFT ERROR", new ValueEntry("Degrees", 0) },
        { "HEADING INDICATOR", new ValueEntry("Degrees", 0) },
        { "THROTTLE LOWER LIMIT", new ValueEntry("Percent", 2) },

        { "NUMBER OF ENGINES", null },
        { "MASTER IGNITION SWITCH", null },
        { "ENG COMBUSTION", null },
        { "GENERAL ENG COMBUSTION:1", null },
        { "GENERAL ENG COMBUSTION:2", null },
        { "GENERAL ENG COMBUSTION:3", null },
        { "GENERAL ENG COMBUSTION:4", null },
        { "GENERAL ENG MASTER ALTERNATOR:1", null },
        { "GENERAL ENG MASTER ALTERNATOR:2", null },
        { "GENERAL ENG FUEL PUMP SWITCH:1", null },
        { "GENERAL ENG FUEL PUMP SWITCH:2", null },
        { "GENERAL ENG FUEL PUMP SWITCH:3", null },
        { "GENERAL ENG FUEL PUMP SWITCH:4", null },
        { "GENERAL ENG FUEL PUMP SWITCH EX1:1", null },
        { "GENERAL ENG FUEL PUMP SWITCH EX1:2", null },
        { "GENERAL ENG FUEL PUMP SWITCH EX1:3", null },
        { "GENERAL ENG FUEL PUMP SWITCH EX1:4", null },
        { "GENERAL ENG FUEL PUMP ON:1", null },
        { "GENERAL ENG FUEL PUMP ON:2", null },
        { "GENERAL ENG FUEL PUMP ON:3", null },
        { "GENERAL ENG FUEL PUMP ON:4", null },
        { "GENERAL ENG STARTER:1", null },
        { "GENERAL ENG STARTER:2", null },
        { "GENERAL ENG STARTER:3", null },
        { "GENERAL ENG STARTER:4", null },
        { "GENERAL ENG GENERATOR SWITCH:1", null },
        { "GENERAL ENG GENERATOR SWITCH:2", null },
        { "GENERAL ENG GENERATOR SWITCH:3", null },
        { "GENERAL ENG GENERATOR SWITCH:4", null },
        { "GENERAL ENG GENERATOR ACTIVE:1", null },
        { "GENERAL ENG GENERATOR ACTIVE:2", null },
        { "GENERAL ENG GENERATOR ACTIVE:3", null },
        { "GENERAL ENG GENERATOR ACTIVE:4", null },
        { "GENERAL ENG ANTI ICE POSITION:1", null },
        { "GENERAL ENG ANTI ICE POSITION:2", null },
        { "GENERAL ENG ANTI ICE POSITION:3", null },
        { "GENERAL ENG ANTI ICE POSITION:4", null },
        { "GENERAL ENG FUEL VALVE:1", null },
        { "GENERAL ENG FUEL VALVE:2", null },
        { "GENERAL ENG FUEL VALVE:3", null },
        { "GENERAL ENG FUEL VALVE:4", null },
        { "GENERAL ENG STARTER ACTIVE", null },
        { "TURB ENG IGNITION ON", null },
        { "TURB ENG MASTER STARTER SWITCH", null },
        { "TURB ENG AFTERBURNER STAGE ACTIVE", null },
        { "FUEL TANK SELECTOR:1", null },
        { "FUEL TANK SELECTOR:2", null },
        { "FUEL TANK SELECTOR:3", null },
        { "FUEL TANK SELECTOR:4", null },
        { "FUEL TRANSFER PUMP ON:1", null },
        { "FUEL TRANSFER PUMP ON:2", null },
        { "FUEL TRANSFER PUMP ON:3", null },
        { "FUEL TRANSFER PUMP ON:4", null },
        { "NUM FUEL SELECTORS", null },
        { "UNLIMITED FUEL", null },
        { "LIGHT STROBE", null },
        { "LIGHT PANEL", null },
        { "LIGHT LANDING", null },
        { "LIGHT TAXI", null },
        { "LIGHT BEACON", null },
        { "LIGHT NAV", null },
        { "LIGHT LOGO", null },
        { "LIGHT WING", null },
        { "LIGHT RECOGNITION", null },
        { "LIGHT CABIN", null },
        { "LIGHT TAXI ON", null },
        { "LIGHT STROBE ON", null },
        { "LIGHT PANEL ON", null },
        { "LIGHT RECOGNITION ON", null },
        { "LIGHT WING ON", null },
        { "LIGHT LOGO ON", null },
        { "LIGHT CABIN ON", null },
        { "LIGHT CABIN ON:1", null },
        { "LIGHT CABIN ON:2", null },
        { "LIGHT CABIN ON:3", null },
        { "LIGHT CABIN ON:4", null },
        { "LIGHT HEAD ON", null },
        { "LIGHT BRAKE ON", null },
        { "LIGHT NAV ON", null },
        { "LIGHT BEACON ON", null },
        { "LIGHT LANDING ON", null },
        { "LIGHT PANEL POWER SETTING:1", null },
        { "LIGHT PANEL POWER SETTING:2", null },
        { "LIGHT PANEL POWER SETTING:3", null },
        { "LIGHT PANEL POWER SETTING:4", null },
        { "LIGHT CABIN POWER SETTING:1", null },
        { "LIGHT CABIN POWER SETTING:2", null },
        { "LIGHT CABIN POWER SETTING:3", null },
        { "LIGHT CABIN POWER SETTING:4", null },
        { "PROP DEICE SWITCH:1", null },
        { "PROP DEICE SWITCH:2", null },
        { "PROP DEICE SWITCH:3", null },
        { "PROP DEICE SWITCH:4", null },
        { "SIM ON GROUND", null },
        { "STALL WARNING", null },
        { "OVERSPEED WARNING", null },
        { "ATTITUDE CAGE", null },
        { "AVIONICS MASTER SWITCH", null },
        { "DME SOUND", null },
        { "TACAN DME SOUND", null },
        { "MARKER SOUND", null },
        { "INNER MARKER", null },
        { "MIDDLE MARKER", null },
        { "OUTER MARKER", null },
        { "HSI CDI NEEDLE", null },
        { "HSI GSI NEEDLE", null },
        { "HSI CDI NEEDLE VALID", null },
        { "HSI GSI NEEDLE VALID", null },
        { "HSI BEARING VALID", null },
        { "HSI HAS LOCALIZER", null },
        { "GPS IS ACTIVE FLIGHT PLAN", null },
        { "GPS IS ACTIVE WAY POINT", null },
        { "GPS IS ARRIVED", null },
        { "GPS IS DIRECTTO FLIGHTPLAN", null },
        { "GPS WP PREV VALID", null },
        { "GPS FLIGHT PLAN WP INDEX", null },
        { "GPS FLIGHT PLAN WP COUNT", null },
        { "GPS IS ACTIVE WP LOCKED", null },
        { "GPS IS APPROACH LOADED", null },
        { "GPS IS APPROACH ACTIVE", null },
        { "GPS APPROACH IS WP RUNWAY", null },
        { "GPS APPROACH APPROACH INDEX", null },
        { "GPS APPROACH TRANSITION INDEX", null },
        { "GPS APPROACH IS FINAL", null },
        { "GPS APPROACH IS MISSED", null },
        { "GPS APPROACH WP INDEX", null },
        { "GPS APPROACH WP COUNT", null },
        { "GPS DRIVES NAV1", null },
        { "COM RECIEVE ALL", null },
        { "COM RECEIVE ALL", null },
        { "COM TRANSMIT:1", null },
        { "COM TRANSMIT:2", null },
        { "COM STATUS:1", null },
        { "COM STATUS:2", null },
        { "COM AVAILABLE", null },
        { "COM TEST:1", null },
        { "COM TEST:2", null },
        { "ADF IDENT", null },
        { "ADF NAME", null },
        { "NAV IDENT", null },
        { "NAV NAME", null },
        { "TACAN IDENT", null },
        { "TACAN NAME", null },
        { "NAV GLIDE SLOPE", null },
        { "SELECTED DME", null },
        { "GPS WP NEXT ID", null },
        { "GPS WP PREV ID", null },
        { "BRAKE PARKING POSITION", null },
        { "BRAKE PARKING INDICATOR", null },
        { "SPOILERS ARMED", null },
        { "FLAPS HANDLE INDEX", null },
        { "FLAPS NUM HANDLE POSITIONS", null },
        { "FLAP DAMAGE BY SPEED", null },
        { "FLAP SPEED EXCEEDED", null },
        { "ALTERNATE STATIC SOURCE OPEN", null },
        { "FOLDING WING HANDLE POSITION", null },
        { "FUEL DUMP SWITCH", null },
        { "AUTOPILOT AVAILABLE", null },
        { "AUTOPILOT MASTER", null },
        { "AUTOPILOT DISENGAGED", null },
        { "AUTOPILOT NAV SELECTED", null },
        { "AUTOPILOT WING LEVELER", null },
        { "AUTOPILOT NAV1 LOCK", null },
        { "AUTOPILOT HEADING LOCK", null },
        { "AUTOPILOT HEADING SLOT INDEX", null },
        { "AUTOPILOT ALTITUDE LOCK", null },
        { "AUTOPILOT ALTITUDE SLOT INDEX", null },
        { "AUTOPILOT ATTITUDE HOLD", null },
        { "AUTOPILOT GLIDESLOPE HOLD", null },
        { "AUTOPILOT APPROACH HOLD", null },
        { "AUTOPILOT BACKCOURSE HOLD", null },
        { "AUTOPILOT PITCH HOLD", null },
        { "AUTOPILOT FLIGHT DIRECTOR ACTIVE", null },
        { "AUTOPILOT AIRSPEED HOLD", null },
        { "AUTOPILOT SPEED SLOT INDEX", null },
        { "AUTOPILOT FLIGHT LEVEL CHANGE", null },
        { "AUTOPILOT MACH HOLD", null },
        { "AUTOPILOT MACH HOLD VAR", null },
        { "AUTOPILOT YAW DAMPER", null },
        { "AUTOPILOT RPM HOLD VAR", null },
        { "AUTOPILOT THROTTLE ARM", null },
        { "AUTOPILOT TAKEOFF POWER ACTIVE", null },
        { "AUTOTHROTTLE ACTIVE", null },
        { "AUTOPILOT VERTICAL HOLD", null },
        { "AUTOPILOT RPM HOLD", null },
        { "FLY BY WIRE ELAC SWITCH", null },
        { "FLY BY WIRE FAC SWITCH", null },
        { "FLY BY WIRE SEC SWITCH", null },
        { "FLY BY WIRE ELAC FAILED", null },
        { "FLY BY WIRE FAC FAILED", null },
        { "FLY BY WIRE SEC FAILED", null },
        { "IS GEAR RETRACTABLE", null },
        { "IS GEAR SKIS", null },
        { "IS GEAR FLOATS", null },
        { "IS GEAR SKIDS", null },
        { "IS GEAR WHEELS", null },
        { "GEAR HANDLE POSITION", null },
        { "TAILWHEEL LOCK ON", null },
        { "AUTO BRAKE SWITCH CB", null },
        { "GEAR EMERGENCY HANDLE POSITION", null },
        { "ANTISKID BRAKES ACTIVE", null },
        { "RETRACT FLOAT SWITCH", null },
        { "GEAR DAMAGE BY SPEED", null },
        { "GEAR SPEED EXCEEDED", null },
        { "NOSEWHEEL LOCK ON", null },
        { "AMBIENT IN CLOUD", null },
        { "SMOKE ENABLE", null },
        { "PITOT HEAT", null },
        { "IS TAIL DRAGGER", null },
        { "ELECTRICAL MASTER BATTERY", null },
        { "ELECTRICAL MASTER BATTERY:1", null },
        { "ELECTRICAL MASTER BATTERY:2", null },
        { "ELECTRIC GPU ACTIVE", null },
        { "ELECTRIC GPU SWITCH", null },
        { "CIRCUIT GENERAL PANEL ON", null },
        { "CIRCUIT FLAP MOTOR ON", null },
        { "CIRCUIT GEAR MOTOR ON", null },
        { "CIRCUIT AUTOPILOT ON", null },
        { "CIRCUIT AVIONICS ON", null },
        { "CIRCUIT PITOT HEAT ON", null },
        { "CIRCUIT PROP SYNC ON", null },
        { "CIRCUIT AUTO FEATHER ON", null },
        { "CIRCUIT AUTO BRAKES ON", null },
        { "CIRCUIT STANDY VACUUM ON", null },
        { "CIRCUIT MARKER BEACON ON", null },
        { "CIRCUIT GEAR WARNING ON", null },
        { "CIRCUIT HYDRAULIC PUMP ON", null },
        { "STRUCTURAL DEICE SWITCH", null },
        { "APPLY HEAT TO SYSTEMS", null },
        { "IS USER SIM", null },
        { "LABEL SUPPORTED", null },
        { "SIM DISABLED", null },
        { "ATC HEAVY", null },
        { "AUTO COORDINATION", null },
        { "REALISM", null },
        { "TRUE AIRSPEED SELECTED", null },
        { "IS SLEW ACTIVE", null },
        { "IS SLEW ALLOWED", null },
        { "PAYLOAD STATION COUNT", null },
        { "USER INPUT ENABLED", null },
        { "CATEGORY", null },
        { "SIGMA SQRT", null },
        { "VARIOMETER SWITCH", null },
        { "TURN INDICATOR SWITCH", null },
        { "PANEL ANTI ICE SWITCH", null },
        { "PAYLOAD STATION NAME", null },
        { "WATER BALLAST VALVE", null },
        { "FULL THROTTLE THRUST TO WEIGHT RATIO", null },
        { "PROP AUTO CRUISE ACTIVE", null },
        { "DROPPABLE OBJECTS UI NAME", null },
        { "HYDRAULIC SWITCH", null },
        { "REALISM CRASH WITH OTHERS", null },
        { "REALISM CRASH DETECTION", null },
        { "MANUAL INSTRUMENT LIGHTS", null },
        { "RAD INS SWITCH", null },
        { "SURFACE INFO VALID", null },
        { "PUSHBACK WAIT", null },
        { "TOW CONNECTION", null },
        { "APU GENERATOR SWITCH", null },
        { "APU GENERATOR ACTIVE", null },
        { "APU ON FIRE DETECTED", null },
        { "PRESSURIZATION DUMP SWITCH", null },
        { "FIRE BOTTLE SWITCH", null },
        { "FIRE BOTTLE DISCHARGED", null },
        { "CABIN NO SMOKING ALERT SWITCH", null },
        { "CABIN SEATBELTS ALERT SWITCH", null },
        { "GPWS WARNING", null },
        { "GPWS SYSTEM ACTIVE", null },
        { "IS LATITUDE LONGITUDE FREEZE ON", null },
        { "IS ALTITUDE FREEZE ON", null },
        { "IS ATTITUDE FREEZE ON", null },
        { "ENG TORQUE:1", null },
        { "ENG TORQUE:2", null },
        { "ENG TORQUE:3", null },
        { "ENG TORQUE:4", null },
        { "TURB ENG FREE TURBINE TORQUE:1", null },
        { "TURB ENG FREE TURBINE TORQUE:2", null },
        { "TURB ENG FREE TURBINE TORQUE:3", null },
        { "TURB ENG FREE TURBINE TORQUE:4", null },
        { "TRANSPONDER CODE:1", null },
        { "TRANSPONDER STATE:1", null },
        { "NAV SOUND:1", null },
        { "NAV SOUND:2", null },
        { "SIMULATION RATE", null },
        { "COM SPACING MODE", null },
        { "ANGLE OF ATTACK INDICATOR", null },
        { "PLANE IN PARKING STATE", null },
        { "MASTER CAUTION ACTIVE", null },
        { "MASTER WARNING ACTIVE", null },
        { "MASTER CAUTION ACKNOWLEDGED", null },
        { "MASTER WARNING ACKNOWLEDGED", null },
        { "RECIP ENG LEFT MAGNETO:1", null },
        { "RECIP ENG LEFT MAGNETO:2", null },
        { "RECIP ENG LEFT MAGNETO:3", null },
        { "RECIP ENG LEFT MAGNETO:4", null },
        { "RECIP ENG RIGHT MAGNETO:1", null },
        { "RECIP ENG RIGHT MAGNETO:2", null },
        { "RECIP ENG RIGHT MAGNETO:3", null },
        { "RECIP ENG RIGHT MAGNETO:4", null },

        { "ABSOLUTE TIME", null },
        { "ZULU TIME", null },
        { "LOCAL TIME", null },
    };

    public static bool IsKnown(this string value)
        => availableValues.ContainsKey(value);

    public static string GetUnit(this string value, string? unit)
    {
        if (!string.IsNullOrEmpty(unit))
        {
            // TODO: add some validation
            return unit;
        }
        else if (availableValues.TryGetValue(value, out var availableEntry) && availableEntry != null)
        {
            return availableEntry.Unit;
        }
        return DEFAULT_UNIT;
    }

    public static int GetDecimals(this string value, int? decimals = null)
    {
        if (decimals.HasValue)
        {
            return decimals.Value;
        }
        else if (availableValues.TryGetValue(value, out var availableEntry) && availableEntry != null)
        {
            return availableEntry.Decimals;
        }

        return DEFAULT_DECIMALS;
    }
}
